{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DataSource\",\"SalesPivot\",\"Calendar\",\"Sales\",\"Customer\",\"Products\",\"CountryCodes\",\"ProductCategories\",\"CustomerProductBridge\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.136.1478.0 (24.09)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "expressions": [
      {
        "name": "DataSource",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "description": "Enter path to source file Sample Company Data.xlsx",
        "expression": "\"C:\\_GitHub\\PowerBI_Demo\\data\\Sample Company Data.xlsx\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d578418f-6f30-4204-b46c-046918003c17"
      }
    ],
    "relationships": [
      {
        "name": "ab1bdd3b-bdbe-4b91-b7ce-32273b41b66b",
        "fromColumn": "OrderDate",
        "fromTable": "SalesPivot",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c8b460d3-b391-4ba6-9e21-0b31b1700fb3"
      },
      {
        "name": "6ae1203f-f746-4cc1-ba74-acb08dceb820",
        "fromColumn": "CalendarDate",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2369a4b8-a7ca-4708-a561-b7b0836411a1"
      },
      {
        "name": "80ac53a2-98e5-48fa-af5e-915fd081201b",
        "fromColumn": "FiscalPYDate",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_649860b2-8b3d-4ed7-bab8-81fd1cb0fba7"
      },
      {
        "name": "b9cf8b57-5277-466b-abaa-25416ce470a7",
        "fromColumn": "FiscalPPDate",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_044f9809-a4c2-4ead-9bd0-34c0bfec8849"
      },
      {
        "name": "cf49d188-c28a-4654-a8f7-f5930f7bc8ce",
        "fromColumn": "FiscalPQDate",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_22cf224a-5fa3-458e-a89d-33c4400ff5c0"
      },
      {
        "name": "7c5b171a-bf85-4aeb-bb97-698aa5065967",
        "fromColumn": "DateKey",
        "fromTable": "SalesPivot",
        "toColumn": "DateKey",
        "toTable": "Calendar"
      },
      {
        "name": "feee0786-7986-48c9-bd84-d7a121feacbf",
        "fromColumn": "OrderDateAfterFirstDate",
        "fromTable": "SalesPivot",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f581cd40-b376-48ff-bbdf-a807a8afdada"
      },
      {
        "name": "e2d4c13f-b3d6-4788-a013-d3ff5b7c2438",
        "fromColumn": "OrderDateAfterFirstMonth",
        "fromTable": "SalesPivot",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2342d329-7f9f-478d-aa5f-37efe59a8003"
      },
      {
        "name": "c7c8aea1-f13f-459c-ab2b-3d8cc99c02fa",
        "fromColumn": "BirthDate",
        "fromTable": "Customer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_658f918d-6afb-47b1-a543-93834dba1dd4"
      },
      {
        "name": "b872ddfd-3b03-41fb-bc35-a032052be36c",
        "fromColumn": "DateFirstPurchase",
        "fromTable": "Customer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b6a9521f-0ebc-4753-8251-bfe1e184c038"
      },
      {
        "name": "9ffc2b5b-43c1-4aca-bfb5-8471fb6df363",
        "fromColumn": "StartDate",
        "fromTable": "Products",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5dc773a6-a3b2-4bdb-9b3f-5484aa38e464"
      },
      {
        "name": "52cb8cbf-667f-4e08-9ad5-51394a9d6186",
        "fromColumn": "EndDate",
        "fromTable": "Products",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_61c7a7cc-d989-45fc-85ae-3996feaf02e1"
      },
      {
        "name": "f4253e86-df82-4733-9a1d-2dee854323bc",
        "fromColumn": "CustomerKey",
        "fromTable": "SalesPivot",
        "toColumn": "CustomerKey",
        "toTable": "Customer"
      },
      {
        "name": "9b13db2e-eecd-4d16-8175-3d5c12d816ef",
        "fromColumn": "CustomerKey",
        "fromTable": "Sales",
        "toColumn": "CustomerKey",
        "toTable": "Customer"
      },
      {
        "name": "acebed96-6d70-4592-bad1-e263e5791c34",
        "fromColumn": "DateKey",
        "fromTable": "Sales",
        "toColumn": "DateKey",
        "toTable": "Calendar"
      },
      {
        "name": "388342ab-4d23-45d2-95a6-17e4d015c759",
        "fromColumn": "ProductKey",
        "fromTable": "Sales",
        "toColumn": "ProductKey",
        "toTable": "Products"
      },
      {
        "name": "a7de2bd3-0073-4769-9910-158c7b4acaa7",
        "fromColumn": "Country",
        "fromTable": "Sales",
        "toColumn": "Country",
        "toTable": "CountryCodes"
      },
      {
        "name": "92ba4652-47c3-4cdf-82ee-6183cc045d6f",
        "fromColumn": "Subcategory",
        "fromTable": "Products",
        "toColumn": "Subcategory",
        "toTable": "ProductCategories"
      },
      {
        "name": "044d7dd6-bd53-40ff-b2f8-1ba009743941",
        "fromColumn": "CustomerKey",
        "fromTable": "CustomerProductBridge",
        "toColumn": "CustomerKey",
        "toTable": "Customer"
      },
      {
        "name": "e12a7c34-c93e-456f-94ac-f28f58b2440e",
        "fromColumn": "ProductKey",
        "fromTable": "CustomerProductBridge",
        "toColumn": "ProductKey",
        "toTable": "Products"
      },
      {
        "name": "75915f19-0994-44a2-938c-05b14ea4e517",
        "fromColumn": "CustomerDateKey",
        "fromTable": "Sales",
        "isActive": false,
        "toColumn": "CustomerDateKey",
        "toTable": "SalesPivot"
      },
      {
        "name": "514d4541-7735-4b70-bd95-b719c8d359e3",
        "fromColumn": "PPDate",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_03dee372-2887-46e3-a805-4571883844a7"
      },
      {
        "name": "34e4f9c7-2da1-49d8-8a87-6908961a1874",
        "fromColumn": "PQDate",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_087140e2-8c67-4ae1-924c-877a5c633c8d"
      },
      {
        "name": "22fdb283-4c52-411c-adb1-1a450af8297e",
        "fromColumn": "PYDate",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_70a5489d-f80c-4199-9137-22032995a46a"
      },
      {
        "name": "3f27e290-4c1f-4d91-8c53-71ed74817997",
        "fromColumn": "FiscalDate",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_21888ed1-f392-4961-87ce-7ba785fc873f"
      },
      {
        "name": "0f864fe2-6f6c-443a-9940-42e605ef0da0",
        "fromColumn": "MonthYearDate",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_52b355b8-60be-40d8-bb59-7ca60ba849df"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "SalesPivot",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Diabolical\\Columns",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1d8c5fa2-dfc0-4f0b-ab53-c334b5a8f00a",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "displayFolder": "Diabolical\\Columns",
            "formatString": "yyyy-mm-dd",
            "isHidden": true,
            "lineageTag": "47d65cac-6ea3-45b9-abb4-4a5f212e4f56",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c8b460d3-b391-4ba6-9e21-0b31b1700fb3"
                },
                "isDefault": true,
                "relationship": "ab1bdd3b-bdbe-4b91-b7ce-32273b41b66b"
              }
            ]
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Diabolical\\Columns",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8c02a0d2-e00b-4350-8744-1276c7085994",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "displayFolder": "Diabolical\\Columns",
            "isHidden": true,
            "lineageTag": "3b7b665e-a164-41d9-86c0-87c2ddf5e642",
            "sourceColumn": "CustomerDateKey",
            "summarizeBy": "none"
          },
          {
            "name": "RankCustDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Diabolical\\Columns",
            "expression": [
              "RANKX(",
              "    FILTER(",
              "        SalesPivot,",
              "        SalesPivot[CustomerKey] = EARLIER( SalesPivot[CustomerKey] )",
              "    ),",
              "    SalesPivot[OrderDate],",
              "    ,",
              "    ASC,",
              "    DENSE",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f80dc5bc-d232-4abb-908c-0e26323db4af",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "OrderDateAfterFirstDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "displayFolder": "Diabolical\\Columns",
            "expression": [
              "VAR CurrentCustomerKey = SalesPivot[CustomerKey]",
              "VAR FirstOrderDate =",
              "    CALCULATE(",
              "        MIN( SalesPivot[OrderDate] ),",
              "        FILTER(",
              "            SalesPivot,",
              "            SalesPivot[CustomerKey] = CurrentCustomerKey",
              "                && SalesPivot[RankCustDate] = 1",
              "        )",
              "    )",
              "VAR OrderAfterFirstDate =",
              "    CALCULATE(",
              "        MIN( SalesPivot[OrderDate] ),",
              "        FILTER(",
              "            SalesPivot,",
              "            SalesPivot[CustomerKey] = CurrentCustomerKey",
              "                && SalesPivot[OrderDate] <> FirstOrderDate",
              "        )",
              "    )",
              "RETURN",
              "    IF(",
              "        SalesPivot[RankCustDate] <> 1,",
              "        BLANK( ),",
              "        IF(",
              "            ISBLANK( OrderAfterFirstDate ),",
              "            BLANK( ),",
              "            OrderAfterFirstDate",
              "        )",
              "    )"
            ],
            "formatString": "yyyy-mm-dd",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "39ada9f6-ea0a-494e-9390-5555bd01c602",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f581cd40-b376-48ff-bbdf-a807a8afdada"
                },
                "isDefault": true,
                "relationship": "feee0786-7986-48c9-bd84-d7a121feacbf"
              }
            ]
          },
          {
            "name": "OrderDateAfterFirstMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "displayFolder": "Diabolical\\Columns",
            "expression": [
              "VAR CurrentCustomerKey = SalesPivot[CustomerKey]",
              "VAR FirstOrderDate =",
              "    CALCULATE(",
              "        MIN( SalesPivot[OrderDate] ),",
              "        FILTER(",
              "            SalesPivot,",
              "            SalesPivot[CustomerKey] = CurrentCustomerKey",
              "                && SalesPivot[RankCustDate] = 1",
              "        )",
              "    )",
              "VAR FirstOrderMonth = MONTH( FirstOrderDate )",
              "VAR FirstOrderYear = YEAR( FirstOrderDate )",
              "VAR OrderAfterFirstMonth =",
              "    CALCULATE(",
              "        MIN( SalesPivot[OrderDate] ),",
              "        FILTER(",
              "            SalesPivot,",
              "            SalesPivot[CustomerKey] = CurrentCustomerKey",
              "                && ( MONTH( SalesPivot[OrderDate] ) <> FirstOrderMonth",
              "                || YEAR( SalesPivot[OrderDate] ) <> FirstOrderYear )",
              "        )",
              "    )",
              "RETURN",
              "    IF(",
              "        SalesPivot[RankCustDate] <> 1,",
              "        BLANK( ),",
              "        IF(",
              "            ISBLANK( OrderAfterFirstMonth ),",
              "            BLANK( ),",
              "            OrderAfterFirstMonth",
              "        )",
              "    )"
            ],
            "formatString": "yyyy-mm-dd",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "300f19cf-30cf-4054-b78c-b9838b9b6da1",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2342d329-7f9f-478d-aa5f-37efe59a8003"
                },
                "isDefault": true,
                "relationship": "e2d4c13f-b3d6-4788-a013-d3ff5b7c2438"
              }
            ]
          },
          {
            "name": "FlagWithin90Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Diabolical\\Columns",
            "expression": [
              "VAR DaysBetweenFirstAndSecond =",
              "    SalesPivot[OrderDateAfterFirstDate] - SalesPivot[OrderDate]",
              "RETURN",
              "    IF(",
              "        NOT ( ISBLANK( SalesPivot[OrderDateAfterFirstDate] ) )",
              "            && NOT ( ISBLANK( SalesPivot[OrderDate] ) )",
              "            && SalesPivot[RankCustDate] = 1",
              "            && DaysBetweenFirstAndSecond > 0",
              "            && DaysBetweenFirstAndSecond <= 90,",
              "        1,",
              "        BLANK( )",
              "    )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "dc3eb206-30ac-43af-84db-d4afca1bf490",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "FlagWithin3Months",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "displayFolder": "Diabolical\\Columns",
            "expression": [
              "IF(",
              "    NOT ( ISBLANK( SalesPivot[OrderDate] ) )",
              "        && NOT ( ISBLANK( SalesPivot[OrderDateAfterFirstMonth] ) )",
              "        && ( ( YEAR( SalesPivot[OrderDateAfterFirstMonth] )",
              "        = YEAR( SalesPivot[OrderDate] )",
              "        && MONTH( SalesPivot[OrderDateAfterFirstMonth] )",
              "        > MONTH( SalesPivot[OrderDate] )",
              "        && MONTH( SalesPivot[OrderDateAfterFirstMonth] )",
              "        <= MONTH( SalesPivot[OrderDate] ) + 3 )",
              "        || ( MONTH( SalesPivot[OrderDate] ) > 9",
              "        && YEAR( SalesPivot[OrderDateAfterFirstMonth] )",
              "        = YEAR( SalesPivot[OrderDate] ) + 1",
              "        && MONTH( SalesPivot[OrderDateAfterFirstMonth] )",
              "        <= ( MONTH( SalesPivot[OrderDate] ) + 3 ) - 12 ) ),",
              "    1,",
              "    BLANK( )",
              ")"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "89f1266f-cd0b-4fc4-b4b1-5f00819a41a8",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "cee6241c-82eb-4d64-a2f3-36e45be29189",
        "measures": [
          {
            "name": "Distinct Customer Count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "displayFolder": "Diabolical\\Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT( SalesPivot[CustomerKey] ),",
              "    SalesPivot[RankCustDate] = 1",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "75fe8350-4427-4f7b-8ea6-349d9c0e532e"
          },
          {
            "name": "CountWithin90Days",
            "displayFolder": "Diabolical\\Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( SalesPivot[FlagWithin90Days] ),",
              "    SalesPivot[RankCustDate] = 1",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b72caf7b-1018-4752-a882-80d9d33ac2a9"
          },
          {
            "name": "CountWithin3Months",
            "displayFolder": "Diabolical\\Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( SalesPivot[FlagWithin3Months] ),",
              "    SalesPivot[RankCustDate] = 1",
              ")"
            ],
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "80f513de-e6fe-4b99-9cf2-a08232d7cda9"
          },
          {
            "name": "% Returned in 90d",
            "displayFolder": "Diabolical\\Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DIVIDE( [CountWithin90Days], [Distinct Customer Count] ),",
              "    SalesPivot[RankCustDate] = 1",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ce1ac968-93ad-4cc9-b10c-7379a287d177"
          },
          {
            "name": "% Returned in 3mo",
            "displayFolder": "Diabolical\\Measures",
            "expression": [
              "",
              "CALCULATE(",
              "    DIVIDE( [CountWithin3Months], [Distinct Customer Count] ),",
              "    SalesPivot[RankCustDate] = 1",
              ")",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "11692e78-06f4-4a7d-a37f-bf21f2e207c1"
          }
        ],
        "partitions": [
          {
            "name": "SalesPivot",
            "mode": "import",
            "source": {
              "expression": [
                "// SalesPivot + 20 years for Clutch.Net tutorial and demo - Tom Sampson © Clutch.Net 2023",
                "// free to use under the MIT License. See project LICENSE for more details.",
                "",
                "let",
                "    DataSourceParam = #\"DataSource\",",
                "    // Load the Sales data from the Excel file",
                "    Source = Excel.Workbook(File.Contents(DataSourceParam), null, true),",
                "    ",
                "    SalesData = Source{[Item=\"Sales\",Kind=\"Sheet\"]}[Data],",
                "",
                "    // Promote headers",
                "    PromotedHeaders = Table.PromoteHeaders(SalesData, [PromoteAllScalars=true]),",
                "",
                "    // Adjust the OrderDate by adding 20 years and transform it to a Date type",
                "    AdjustedDate = Table.TransformColumns(PromotedHeaders, {\"OrderDate\", each Date.From(Date.AddYears(_, 20))}),",
                "",
                "    // Filter rows where OrderDate <= today's date",
                "    FilteredRows = Table.SelectRows(AdjustedDate, each [OrderDate] <= Date.From(DateTime.LocalNow())),    ",
                "",
                "    // Add DateKey column based on the Adjusted OrderDate. This is an integer version of the date",
                "    DateKey = Table.AddColumn(",
                "        FilteredRows, ",
                "        \"DateKey\", ",
                "        each Text.From(Date.Year([OrderDate])) & Text.End(Text.PadStart(Text.From(Date.Month([OrderDate]), \"en-US\"), 2, \"0\"), 2) & Text.End(Text.PadStart(Text.From(Date.Day([OrderDate]), \"en-US\"), 2, \"0\"), 2)",
                "    ),",
                "",
                "    // Ensure CustomerKey and DateKey are in text format for concatenation",
                "    TextCustomerOrderKey = Table.TransformColumnTypes(",
                "        DateKey, ",
                "        {{\"CustomerKey\", type text}, {\"DateKey\", type text}}",
                "    ),",
                "",
                "    // Add CustomerDateKey column by concatenating CustomerKey and DateKey",
                "    CustomerDateKey = Table.AddColumn(",
                "        TextCustomerOrderKey, ",
                "        \"CustomerDateKey\", ",
                "        each Text.From([CustomerKey]) & Text.From([DateKey])",
                "    ),",
                "",
                "    // Convert the concatenated columns to whole numbers and the OrderDate to Date",
                "    NumericKeys = Table.TransformColumnTypes(",
                "        CustomerDateKey, {",
                "            {\"CustomerKey\", Int64.Type},",
                "            {\"DateKey\", Int64.Type},",
                "            {\"OrderDate\", type date}",
                "        }",
                "    ),",
                "",
                "    // Remove unnecessary columns",
                "    #\"Removed Columns\" = Table.RemoveColumns(",
                "        NumericKeys,",
                "        {\"ProductKey\", \"SalesTerritoryKey\", \"SalesOrderNumber\", \"SalesOrderLineNumber\", \"OrderQuantity\", \"DiscountAmount\", \"ProductStandardCost\", \"SalesAmount\", \"Territories.Region\", \"Territories.Country\", \"Territories.Continent\"}",
                "    ),",
                "",
                "    // Keep only a distinct set of rows and sort them",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Columns\"),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Removed Duplicates\",{{\"CustomerKey\", Order.Ascending}, {\"DateKey\", Order.Ascending}}),",
                "",
                "    // Reorder columns",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Sorted Rows\",{\"CustomerKey\", \"OrderDate\", \"CustomerDateKey\"})",
                "    ",
                "in",
                "    #\"Reordered Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_a5e07f8e-1667-4b42-a879-7dddbe4f3233",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "55d30e58-3803-4f9a-88df-0a94c2738c9a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d727cf5a-3d85-43b8-bbf6-3da0d9a122b2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "552f9dec-563a-4d1c-b267-0fbbede05649",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9fb3f828-7216-4207-ba62-f4d86ccf1c46",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ab40b926-5bdc-400e-8041-573d1e195cee",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "10c89410-7a8b-4621-939b-da92e9607669",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "18250f7c-8da6-4741-ac97-843e6131bb3e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5e95f70c-6e00-4358-8634-09c9a0a5287d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "425b114d-3422-41b8-beb2-f12b36229436",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "25109904-8201-4d17-b0a4-ace084e67b07",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6c0494ce-b232-4fb9-b415-40ab61bad24a",
                "ordinal": 3
              }
            ],
            "lineageTag": "c1582be6-d482-493f-93a2-03a309318415"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "e0b0f800-ea02-4677-85ac-54c89461de3d",
        "partitions": [
          {
            "name": "DateTableTemplate_a5e07f8e-1667-4b42-a879-7dddbe4f3233",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c8b460d3-b391-4ba6-9e21-0b31b1700fb3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "819fa529-4b27-4c96-bb06-5904f5e848ce",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "79953263-669b-4b21-9eef-67d9f50a2c70",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "19b38bd0-3479-49ed-9a48-6ea26b613236",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a2957c50-50b1-4222-96d4-2e9b93c79ace",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "47e0b590-b3fa-472e-aac9-8f4627b04308",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1ae6a0a2-2944-4898-8cff-762778f4341e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f5fd796a-2819-465c-8c93-dcd8bf486187",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "69fcda98-0295-483d-b1a5-8a731fcfeaf2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a9903269-e055-44af-bd91-e6d7b04ef925",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "fca35bbf-4e96-4888-8b32-747444818d09",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "07180ebb-0cde-4565-8860-6cd50bc83a8b",
                "ordinal": 3
              }
            ],
            "lineageTag": "40d5c6a9-e714-4bd8-b6f0-88fbbee30286"
          }
        ],
        "isHidden": true,
        "lineageTag": "04c80206-c68f-4454-850d-1af611338f08",
        "partitions": [
          {
            "name": "LocalDateTable_c8b460d3-b391-4ba6-9e21-0b31b1700fb3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SalesPivot'[OrderDate])), 1, 1), Date(Year(MAX('SalesPivot'[OrderDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CalendarDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "199e0624-5887-432f-92e2-787200b1f363",
            "sourceColumn": "CalendarDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2369a4b8-a7ca-4708-a561-b7b0836411a1"
                },
                "isDefault": true,
                "relationship": "6ae1203f-f746-4cc1-ba74-acb08dceb820"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6b442ef9-86c1-42d5-b897-e2e6106ccd25",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ff870775-464b-4412-9eec-c881e9f9f714",
            "sourceColumn": "Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8b4bf40d-3bb3-481e-a2d5-9e4723ff9777",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1a3d0eb2-faa7-46f3-b1f0-588a1f6ca8f3",
            "sourceColumn": "Day",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "04c3dda7-2e3a-4313-a4a6-f38593dd891e",
            "sourceColumn": "WeekNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d10bc387-a0d5-4bd8-a599-847e0c3b41ed",
            "sourceColumn": "WeekDay",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b172dba-c45e-44c3-a9d1-bc3c527ff0ac",
            "sourceColumn": "MonthName",
            "summarizeBy": "none"
          },
          {
            "name": "DayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "56c5438d-4df5-410a-ad76-9ab957242f4d",
            "sourceColumn": "DayName",
            "summarizeBy": "none"
          },
          {
            "name": "DayOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f5bb205-c496-4fe0-8c3c-8942ed2887f9",
            "sourceColumn": "DayOfYear",
            "summarizeBy": "sum"
          },
          {
            "name": "IsWeekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "395b3595-8acd-42e9-b586-06f216e635e2",
            "sourceColumn": "IsWeekend",
            "summarizeBy": "none"
          },
          {
            "name": "RelativeDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "255f12be-bca4-4c57-9ee9-e258dd90eae5",
            "sourceColumn": "RelativeDate",
            "summarizeBy": "sum"
          },
          {
            "name": "RelativePeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e80a90ed-86b5-4705-8551-17ca90e9a800",
            "sourceColumn": "RelativePeriod",
            "summarizeBy": "sum"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ce992858-1da1-4f4c-a357-0d8a877e5a02",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalPYDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "9dd73fe4-5f31-4400-bc64-c6277b0920bf",
            "sourceColumn": "FiscalPYDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_649860b2-8b3d-4ed7-bab8-81fd1cb0fba7"
                },
                "isDefault": true,
                "relationship": "80ac53a2-98e5-48fa-af5e-915fd081201b"
              }
            ]
          },
          {
            "name": "FiscalPPDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "3bf2bdf2-706f-430f-b7e5-30326b0e53a9",
            "sourceColumn": "FiscalPPDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_044f9809-a4c2-4ead-9bd0-34c0bfec8849"
                },
                "isDefault": true,
                "relationship": "b9cf8b57-5277-466b-abaa-25416ce470a7"
              }
            ]
          },
          {
            "name": "FiscalPQDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "3236cfba-954d-4535-95b8-b02e79952617",
            "sourceColumn": "FiscalPQDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_22cf224a-5fa3-458e-a89d-33c4400ff5c0"
                },
                "isDefault": true,
                "relationship": "cf49d188-c28a-4654-a8f7-f5930f7bc8ce"
              }
            ]
          },
          {
            "name": "PPDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "28159873-00f4-44e4-a844-dbe0b3a7031b",
            "sourceColumn": "PPDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_03dee372-2887-46e3-a805-4571883844a7"
                },
                "isDefault": true,
                "relationship": "514d4541-7735-4b70-bd95-b719c8d359e3"
              }
            ]
          },
          {
            "name": "PQDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "b22b8386-2a2d-49ff-b886-6f642fdb6236",
            "sourceColumn": "PQDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_087140e2-8c67-4ae1-924c-877a5c633c8d"
                },
                "isDefault": true,
                "relationship": "34e4f9c7-2da1-49d8-8a87-6908961a1874"
              }
            ]
          },
          {
            "name": "PriorPeriodYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a71f6ed4-250f-4e2a-8ff4-1db1892089a8",
            "sourceColumn": "PriorPeriodYear",
            "summarizeBy": "sum"
          },
          {
            "name": "PYDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "17996db0-7f64-4a6f-ae83-963f235374a3",
            "sourceColumn": "PYDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_70a5489d-f80c-4199-9137-22032995a46a"
                },
                "isDefault": true,
                "relationship": "22fdb283-4c52-411c-adb1-1a450af8297e"
              }
            ]
          },
          {
            "name": "FiscalDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "a0ef9d54-102e-4d8a-9fcd-501fcf33ac91",
            "sourceColumn": "FiscalDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_21888ed1-f392-4961-87ce-7ba785fc873f"
                },
                "isDefault": true,
                "relationship": "3f27e290-4c1f-4d91-8c53-71ed74817997"
              }
            ]
          },
          {
            "name": "FiscalYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "83eba0e1-3884-49fd-a8b8-f57adc4134a3",
            "sourceColumn": "FiscalYear",
            "summarizeBy": "sum"
          },
          {
            "name": "FiscalQuarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aa3cb925-1264-4441-8ccb-ffd02781d661",
            "sourceColumn": "FiscalQuarter",
            "summarizeBy": "sum"
          },
          {
            "name": "FiscalPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "07d7bdc1-1d38-4b9e-800f-1d63325c3b8e",
            "sourceColumn": "FiscalPeriod",
            "summarizeBy": "sum"
          },
          {
            "name": "Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "52427e5d-a308-473b-9eac-309bf4ca5b66",
            "sourceColumn": "Period",
            "summarizeBy": "sum"
          },
          {
            "name": "FiscalPriorPeriodYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "156e34a0-7b08-459a-975e-ec961b9697ba",
            "sourceColumn": "FiscalPriorPeriodYear",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "cb87a04f-1fe5-457e-9d7b-853c2d482915",
            "sortByColumn": "MonthYearDate",
            "sourceColumn": "MonthYear",
            "summarizeBy": "none"
          },
          {
            "name": "MonthYearDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Mmm yy",
            "lineageTag": "566c5add-0cd1-4e59-bbb2-de6aed07c3aa",
            "sourceColumn": "MonthYearDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_52b355b8-60be-40d8-bb59-7ca60ba849df"
                },
                "isDefault": true,
                "relationship": "0f864fe2-6f6c-443a-9940-42e605ef0da0"
              }
            ]
          }
        ],
        "lineageTag": "aeea16b9-d8ed-47c3-adb9-1f92bf1c29e2",
        "partitions": [
          {
            "name": "Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "// Generic Power BI Calendar with selective start date - Tom Sampson © Clutch.Net 2023",
                "// free to use under the MIT License. See project LICENSE for more details.",
                "// v 1.1 - 20230910 - Tom S - Added MonthYear text version, in your model use the date version to sort",
                "// v 1.2 - 20230917 - Tom S - Added configurable fiscal date choices",
                "let",
                "    Source = Sales, // Change this to your source",
                "    MinDate = Date.From(Date.StartOfYear(List.Min(Source[OrderDate]))), // Change this to your source column, the calendar coverage will be based on this",
                "    EndDate = Date.From(List.Max(Source[OrderDate])), // this column choice should match the one you made on the line above",
                "    AllDates = List.Dates(MinDate, Duration.Days(EndDate - MinDate) + 1, #duration(1, 0, 0, 0)),",
                "    // Add a parameter for the fiscal year start month.",
                "    // Set this based on your choice:",
                "    // 1 for January (most U.S. companies)",
                "    // 4 for April (U.K. and Japan)",
                "    // 7 for July (for countries like Australia and the start of the federal government's fiscal year in Canada)",
                "    // 10 for October (In the U.S., the federal government's fiscal year starts on October 1st and ends on September 30th)",
                "    FiscalStartMonth = 1, // change this based on your choice",
                "    InitialTable = Table.FromList(AllDates, Splitter.SplitByNothing()),",
                "    RenamedTable = Table.RenameColumns(InitialTable,{{\"Column1\", \"CalendarDate\"}}),",
                "    AddYear = Table.AddColumn(RenamedTable, \"Year\", each Date.Year([CalendarDate]), Int64.Type),",
                "    AddQuarter = Table.AddColumn(AddYear, \"Quarter\", each Date.QuarterOfYear([CalendarDate]), Int64.Type),",
                "    AddMonth = Table.AddColumn(AddQuarter, \"Month\", each Date.Month([CalendarDate]), Int64.Type),",
                "    AddPeriod = Table.AddColumn(AddMonth, \"Period\", each Date.Month([CalendarDate]), Int64.Type),",
                "    AddDay = Table.AddColumn(AddPeriod, \"Day\", each Date.Day([CalendarDate]), Int64.Type),",
                "    AddWeekNumber = Table.AddColumn(AddDay, \"WeekNumber\", each Date.WeekOfYear([CalendarDate]), Int64.Type),",
                "    AddWeekDay = Table.AddColumn(AddWeekNumber, \"WeekDay\", each Date.DayOfWeek([CalendarDate]) + 1, Int64.Type),",
                "    AddMonthName = Table.AddColumn(AddWeekDay, \"MonthName\", each Date.ToText([CalendarDate], \"MMMM\"), Text.Type),",
                "    AddDayName = Table.AddColumn(AddMonthName, \"DayName\", each Date.ToText([CalendarDate], \"dddd\"), Text.Type),",
                "    AddDayOfYear = Table.AddColumn(AddDayName, \"DayOfYear\", each Date.DayOfYear([CalendarDate]), Int64.Type),",
                "    AddIsWeekend = Table.AddColumn(AddDayOfYear, \"IsWeekend\", each if Date.DayOfWeek([CalendarDate], Day.Monday) >= 5 then \"Weekend\" else \"Weekday\", Text.Type),",
                "    AddRelativeDate = Table.AddColumn(AddIsWeekend, \"RelativeDate\", each Duration.Days([CalendarDate] - EndDate), Int64.Type),",
                "    AddRelativePeriod = Table.AddColumn(AddRelativeDate, \"RelativePeriod\", each -(Date.Year([CalendarDate])*12 + Date.Month([CalendarDate]) - (Date.Year(EndDate)*12 + Date.Month(EndDate)) ) * -1, Int64.Type),",
                "    AddDateKey = Table.AddColumn(AddRelativePeriod, \"DateKey\", each [Year]*10000 + [Month]*100 + [Day], Int64.Type),",
                "    AddPPDate = Table.AddColumn(AddDateKey, \"PPDate\", each Date.AddMonths([CalendarDate], -1), Date.Type),",
                "    AddPQDate = Table.AddColumn(AddPPDate, \"PQDate\", each Date.AddQuarters([CalendarDate], -1), Date.Type),",
                "    AddPriorPeriodYear = Table.AddColumn(AddPQDate, \"PriorPeriodYear\", each Date.Year(Date.AddMonths([CalendarDate], -1)), Int64.Type),",
                "    AddPYDate = Table.AddColumn(AddPriorPeriodYear, \"PYDate\", each Date.AddYears([CalendarDate], -1), Date.Type),",
                "    AddMonthYear = Table.AddColumn(AddPYDate, \"MonthYear\", each Text.Start(Date.MonthName([CalendarDate]),3) & \" \" & Text.End(Text.From(Date.Year([CalendarDate])),2)),  ",
                "    IntermediateTable = Table.AddColumn(AddMonthYear, \"MonthYearDate\", each #date(Date.Year([CalendarDate]), Date.Month([CalendarDate]), 1)),",
                "    AddMonthYearDate = Table.TransformColumnTypes(IntermediateTable,{{\"MonthYearDate\", type date}}),",
                "    //Fiscal Dates",
                "    AddFiscalDate = Table.AddColumn(AddMonthYearDate, \"FiscalDate\", each ",
                "        if Date.Month([CalendarDate]) < FiscalStartMonth then Date.AddYears([CalendarDate], -1) else [CalendarDate], Date.Type),",
                "    AddFiscalYear = Table.AddColumn(AddFiscalDate, \"FiscalYear\", each Date.Year([FiscalDate]), Int64.Type),",
                "    AddFiscalQuarter = Table.AddColumn(AddFiscalYear, \"FiscalQuarter\", each ",
                "        let ",
                "            monthDiff = Date.Month([FiscalDate]) - FiscalStartMonth,",
                "            adjustedMonthDiff = if monthDiff < 0 then monthDiff + 12 else monthDiff",
                "        in ",
                "            Number.RoundDown(adjustedMonthDiff / 3) + 1, Int64.Type),",
                "    AddFiscalPeriod = Table.AddColumn(AddFiscalQuarter, \"FiscalPeriod\", each ",
                "        let ",
                "            monthDiff = Date.Month([FiscalDate]) - FiscalStartMonth,",
                "            adjustedMonthDiff = if monthDiff < 0 then monthDiff + 12 else monthDiff",
                "        in ",
                "            adjustedMonthDiff + 1, Int64.Type),",
                "    AddFiscalPPDate = Table.AddColumn(AddFiscalPeriod, \"FiscalPPDate\", each Date.AddMonths([FiscalDate], -1), Date.Type),",
                "    AddFiscalPQDate = Table.AddColumn(AddFiscalPPDate, \"FiscalPQDate\", each Date.AddQuarters([FiscalDate], -1), Date.Type),",
                "    AddFiscalPriorPeriodYear = Table.AddColumn(AddFiscalPQDate, \"FiscalPriorPeriodYear\", each Date.Year([FiscalPPDate]), Int64.Type),",
                "    AddFiscalPYDate = Table.AddColumn(AddFiscalPriorPeriodYear, \"FiscalPYDate\", each ",
                "        Date.AddYears([FiscalDate], -1), Date.Type),    ",
                "    FinalTable = Table.TransformColumnTypes(AddFiscalPYDate,{{\"CalendarDate\", type date}, {\"FiscalPYDate\", type date}})",
                "in",
                "    FinalTable"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2369a4b8-a7ca-4708-a561-b7b0836411a1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "58a97ff7-f356-4a39-bb4a-c0158433f287",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "76b46240-2cb9-4522-9d5e-df9f826a92e9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9d075654-bff9-4d70-b7d3-f02be5fe05f9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0d33304b-5210-4a07-b82e-331c0db6113e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3f87f655-6472-4876-9db4-71810c4c2675",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9d712b77-c35e-42f9-bed8-d1160d009580",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "898f9107-5285-4028-98dc-d8c99b814b5c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6cc62036-fdbe-4063-8ddd-30b8043a62ed",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f80c85f5-dc08-4e7d-a8d5-85e011527b96",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "fc9c847c-bc38-47fd-889f-5907590319f4",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "196b7db7-e941-4ebf-b501-65e52b8984b3",
                "ordinal": 3
              }
            ],
            "lineageTag": "585936cb-dc38-48b3-b4d9-cca852500440"
          }
        ],
        "isHidden": true,
        "lineageTag": "e5e682fa-f462-4dfd-b884-7953fcc2015e",
        "partitions": [
          {
            "name": "LocalDateTable_2369a4b8-a7ca-4708-a561-b7b0836411a1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[CalendarDate])), 1, 1), Date(Year(MAX('Calendar'[CalendarDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_649860b2-8b3d-4ed7-bab8-81fd1cb0fba7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e977f917-4d22-40f7-853b-4207623e3ebc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ddfce07b-fb56-414d-80f3-a8f58ee84c0c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5c5eca6b-7a67-4945-8064-fe9fdf2344ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "484fa575-9493-40e6-a958-993614b2d907",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "96034878-2ab7-4be3-9ed3-3d1e0d5ce740",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "71bc4eba-66c4-4f80-bb06-98716fc6d4e6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1ada1095-9e30-4248-bec3-786c099d19ac",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7ca92208-c543-4207-8924-ec4bee23b41d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "481115cb-e92c-48a3-a707-dec121d3ef99",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f0886279-fcb8-4e3d-86ef-712b9a7464f3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0d530130-ff38-4672-8033-9d6a502bda4a",
                "ordinal": 3
              }
            ],
            "lineageTag": "33e58957-f591-4dc6-a987-7a6fe79eb1c3"
          }
        ],
        "isHidden": true,
        "lineageTag": "b8e26371-622f-486c-8fc0-3ee61734d03e",
        "partitions": [
          {
            "name": "LocalDateTable_649860b2-8b3d-4ed7-bab8-81fd1cb0fba7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[FiscalPYDate])), 1, 1), Date(Year(MAX('Calendar'[FiscalPYDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_044f9809-a4c2-4ead-9bd0-34c0bfec8849",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "17838fc8-9d69-47fe-8520-e7f42eccc865",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3c9d450c-7590-47b3-9880-b50a66addcb7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "25fde446-df69-4288-9114-034674548789",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b84e696b-5bd7-4768-afc8-73545ff3e08c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f4907886-5c62-4247-a531-05f5dd0ff867",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6d8b2f69-0269-4779-aaf4-b0eb02baaad8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ed86aa77-d596-4b78-9cde-0c037f30ca04",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "75697765-0dfa-474c-8459-bf04ed430c40",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "808989c3-9150-489c-b4cc-f9a7021f01bc",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ebc2782f-1b3f-4e8b-8050-6cb849d9a9e1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5a3eae8e-fa91-41a2-9e1a-c3b837222f52",
                "ordinal": 3
              }
            ],
            "lineageTag": "837498b7-ce6d-4a1c-b222-c991267d8976"
          }
        ],
        "isHidden": true,
        "lineageTag": "4f86e299-0de8-474f-96a9-f28e02eaa202",
        "partitions": [
          {
            "name": "LocalDateTable_044f9809-a4c2-4ead-9bd0-34c0bfec8849",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[FiscalPPDate])), 1, 1), Date(Year(MAX('Calendar'[FiscalPPDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_22cf224a-5fa3-458e-a89d-33c4400ff5c0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c1a7053d-5dc0-406d-b950-af8841bea444",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0450aa56-8e4f-4e23-bc1c-4e790bd0438f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a2a4d9d4-d558-4f05-a267-c78bbfe3cb24",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "368b3d0b-d767-4d26-b629-d4710ed8e7a9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fea5861e-46ec-40fe-9a61-aa8a31029194",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "641bb657-9d3a-48ad-acf2-11b66eeeffc3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fd29e389-a5e2-41be-8ae0-ffc22f766b87",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bfddd432-9443-49ed-8062-5459b97c7c1d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "eb51f35f-19a7-4619-b877-714cbc8eb754",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6aaa6b77-e9f0-4db4-b0ae-29d8822ddbde",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c5c9a046-3cae-4048-8687-16d3184c4f30",
                "ordinal": 3
              }
            ],
            "lineageTag": "cd9a4fa0-dc13-45cc-8a19-c01837a05a5c"
          }
        ],
        "isHidden": true,
        "lineageTag": "190e32b7-3bef-45d7-b5b0-cba833e19185",
        "partitions": [
          {
            "name": "LocalDateTable_22cf224a-5fa3-458e-a89d-33c4400ff5c0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[FiscalPQDate])), 1, 1), Date(Year(MAX('Calendar'[FiscalPQDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_f581cd40-b376-48ff-bbdf-a807a8afdada",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "667c9b08-1ee1-450b-8c86-19344161d1df",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "31264afb-d06e-447e-9b84-f3e5e617be20",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c2f55f95-1828-4c0e-9cfe-842f468b0b1b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "07d8b174-b850-43df-986c-5f564ff89fcf",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "20f8e44c-8e80-4819-8bd4-ff861258cfdd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cd08cbef-3a88-490e-b5a6-be3b230d7e87",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "05d9e3ef-1f2d-4ac2-93d7-e0ed7df0a914",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6aaaf21a-a085-471e-a94b-6be6ce80814f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d56c9434-c957-45e9-bc88-4690a4190628",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "09b1d455-9e94-466c-9c7c-30fc8dbbfa87",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a07f3775-6668-4c84-afda-ce26483df1b2",
                "ordinal": 3
              }
            ],
            "lineageTag": "31163e42-b90c-4bf8-84a7-5d2b723f2fdf"
          }
        ],
        "isHidden": true,
        "lineageTag": "f463c3a3-a6c6-44db-a134-791fca092532",
        "partitions": [
          {
            "name": "LocalDateTable_f581cd40-b376-48ff-bbdf-a807a8afdada",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SalesPivot'[OrderDateAfterFirstDate])), 1, 1), Date(Year(MAX('SalesPivot'[OrderDateAfterFirstDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_2342d329-7f9f-478d-aa5f-37efe59a8003",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e40739f0-3907-490e-98ba-992a918d9358",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3fc26113-dcda-4305-93ae-7cfbf7b05399",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ef33d2d3-cbe0-45e1-a640-a1d00ea7724a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fa57e928-573c-487c-b4f8-0706911541e5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a3c1b8b1-d255-4671-b2f0-15559e7bdb53",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0f5ccd41-a976-433f-9f76-987086b73c41",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9ce947a1-cdec-4cd4-a972-5741210c22eb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8501f071-ec12-46ca-a20f-5476582777df",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "20f23f02-6368-43ef-8f6a-c17845d5a4e8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "948ee97c-44e8-44b2-9053-06fbb8c3e8ee",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "12f5c6b5-c336-4abd-98d4-be6b7d849238",
                "ordinal": 3
              }
            ],
            "lineageTag": "9aedb011-79f2-454a-831d-988f92137fb3"
          }
        ],
        "isHidden": true,
        "lineageTag": "119b5b3d-62a0-449f-841d-3edc216cd81f",
        "partitions": [
          {
            "name": "LocalDateTable_2342d329-7f9f-478d-aa5f-37efe59a8003",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SalesPivot'[OrderDateAfterFirstMonth])), 1, 1), Date(Year(MAX('SalesPivot'[OrderDateAfterFirstMonth])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Sales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8706896b-d07b-4be7-9381-8611ba22d2c7",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3386e38b-eb0a-4449-95f8-eb7d3c82eb64",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b1418b64-6d90-41f6-9442-bff63e3a96eb",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "SalesTerritoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9a32d285-1826-43fe-b3b8-6b5178869b2e",
            "sourceColumn": "SalesTerritoryKey",
            "summarizeBy": "count"
          },
          {
            "name": "OrderKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41f6720f-5aa1-4cc7-a6be-f800ee3dcf73",
            "sourceColumn": "OrderKey",
            "summarizeBy": "count"
          },
          {
            "name": "SalesOrderLineNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2a64cf5c-0514-406f-b999-38fe30ec8d82",
            "sourceColumn": "SalesOrderLineNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "OrderQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "#,##0",
            "lineageTag": "39971296-4ad4-4aad-8cf5-e15139e9fd1d",
            "sourceColumn": "OrderQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "DiscountAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "86307f83-f39c-47c6-aa96-6ed6b3c56420",
            "sourceColumn": "DiscountAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "ProductStandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "94f01542-6814-4710-b6d4-34f3811eb8d7",
            "sourceColumn": "ProductStandardCost",
            "summarizeBy": "sum"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "af59801a-dfb1-42aa-947b-43b063e3f2cd",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "sum"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b348b04e-de5b-4915-a241-89bfa9a817c3",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0944652-c45f-4ddc-9ce1-b53008468fa0",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edccfc29-8cd6-4c2b-9327-18141e7a2588",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerOrderKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1daf43ff-f51b-42b2-a9f4-f9ec0cc8e89c",
            "sourceColumn": "CustomerOrderKey",
            "summarizeBy": "count"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "584a406f-9f35-4944-8591-6520acf9e663",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0cf88f33-496d-4507-be95-b21ef792a53e",
            "sourceColumn": "CustomerDateKey",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "0e744440-434b-434f-b864-084ca3999801",
        "measures": [
          {
            "name": "Amt Cost - P01",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P01",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P1\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "b9e5f049-4e59-4a67-b0f9-e4dd5dcf6c1c"
          },
          {
            "name": "Amt Cost - P02",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P02",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P2\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "96bc46f3-80ec-482c-bbc8-93d1564ed2ca"
          },
          {
            "name": "Amt Cost - P03",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P03",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P3\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9633383d-7203-4581-977a-44279494bd10"
          },
          {
            "name": "Amt Cost - P04",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P04",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P4\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "84113acc-1476-4fac-8236-6d053e37ea52"
          },
          {
            "name": "Amt Cost - P05",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P05",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P5\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "42410c86-bddd-4548-aa9f-20793f205d7f"
          },
          {
            "name": "Amt Cost - P06",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P06",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P6\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "2d5d23fd-85bf-4cee-824f-2826b5aaad8c"
          },
          {
            "name": "Amt Cost - P07",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P07",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P7\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "e9bbe20f-10b7-444d-adaf-69b15bddbcc7"
          },
          {
            "name": "Amt Cost - P08",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P08",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P8\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "a75f3a27-99b7-4b95-a364-9c6cd5db3b86"
          },
          {
            "name": "Amt Cost - P09",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P09",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P9\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "b781d261-d717-4f41-bd05-d362ee65b214"
          },
          {
            "name": "Amt Cost - P10",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P10",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P10\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "82ba86c4-9923-42ef-bcec-929df9aa5c9e"
          },
          {
            "name": "Amt Cost - P11",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P11",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P11\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "fb99520f-e03c-4268-8379-46ae4ed46a1d"
          },
          {
            "name": "Amt Cost - P12",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P12",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P12\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "82980420-9592-44a1-a09b-16745082e665"
          },
          {
            "name": "Amt Cost - P13",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P13",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P13\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "c1137bbc-3fb5-4b09-b6e8-21b6ddf3b8c1"
          },
          {
            "name": "Amt Cost - P14",
            "displayFolder": "Amt Cost\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - P14",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P14\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "d29b2c90-babf-4ec8-8799-5bcd85e1bbbc"
          },
          {
            "name": "Amt Cost - Current",
            "description": "Amt Cost - Current",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - Current",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"Current\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "dd4f7438-d2c2-4732-acad-fc8cd7f95e1c"
          },
          {
            "name": "Amt Cost - ITD",
            "description": "Amt Cost  - Inception to Date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - ITD",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"ITD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9587ab8b-58a8-49fc-a81a-0836c7034e4d"
          },
          {
            "name": "Amt Cost - MTD",
            "description": "Amt Cost  - Month to Date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - MTD",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"MTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "d423bded-90f1-44eb-8423-4f29c0048b82"
          },
          {
            "name": "Amt Cost - PP",
            "description": "Amt Cost  - Prior Period",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - PP",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PP\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "63c789c0-fab4-4415-945d-495030e0e436"
          },
          {
            "name": "Amt Cost - PY",
            "description": "Amt Cost  - Prior Year",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - PY",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "68738bf6-7bff-4614-b4d7-a805a51d407c"
          },
          {
            "name": "Amt Cost - PY ITD",
            "description": "Amt Cost  - Prior Year Inception to Date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - PY ITD",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY ITD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "beeea7d4-58fc-4e21-9f89-54f41b8908a1"
          },
          {
            "name": "Amt Cost - PY MTD",
            "description": "Amt Cost  - Prior Year Month to Date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - PY MTD",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY MTD",
              "        \"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "a57057fe-c329-4a22-bbd0-fa1a4ca8609d"
          },
          {
            "name": "Amt Cost - PY QTD",
            "description": "Amt Cost  - Prior Year Quarter to Date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - PY QTD",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "de250890-5818-4623-9777-091bbe5cd37d"
          },
          {
            "name": "Amt Cost - PY YTD",
            "description": "Amt Cost  - Prior Year Year to Date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - PY YTD",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "e853d2c4-f516-449e-ab13-cf2c6d907af7"
          },
          {
            "name": "Amt Cost - QTD",
            "description": "Amt Cost  - Quarter to Date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - QTD",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "cbb8825d-8d45-4ab0-8222-3c26d25d97a7"
          },
          {
            "name": "Amt Cost - YTD",
            "description": "Amt Cost  - Year to Date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - YTD",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "029a1839-866f-46ab-9525-63088f5ae2c4"
          },
          {
            "name": "Amt Cost - YTotal",
            "description": "Amt Cost  - Year Total",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - YTotal",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"YTotal\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "0b76d7d4-a08d-4454-bc4f-f4ab062ca3f7"
          },
          {
            "name": "Amt Cost_input",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Amt Cost  - Input Measure",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost_input",
              "",
              "-- I do this so later on we can add a switch for live currency conversion - Tom Sampson 20230901",
              "SUM ( Sales[ProductStandardCost] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "lineageTag": "977b015f-99d8-4de8-b6c2-e4f7cf48098f"
          },
          {
            "name": "Amt Cost vs PY",
            "description": "Amt Cost  - Current - Prior Year",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost vs PY",
              "",
              "[Amt Cost - Current] - [Amt Cost - PY]"
            ],
            "formatString": "#,##0",
            "lineageTag": "29368d3c-be3f-4393-9fe0-4d9cc72f191c"
          },
          {
            "name": "Amt Cost - Current vs PY %",
            "description": "Amt Cost  - Current vs PY / PY",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - Current vs PY %",
              "",
              "DIVIDE ( [Amt Cost vs PY], [Amt Cost - PY], BLANK ( ) )"
            ],
            "formatString": "#,##0 %",
            "lineageTag": "686cf627-a790-43fd-b334-154ed29e89c3"
          },
          {
            "name": "Amt Cost vs PY %",
            "description": "[Amt Cost vs PY] / [Amt Cost PY] ",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost vs PY %",
              "",
              "IF (",
              "    [Amt Cost vs PY] <> 0 && [Amt Cost - PY] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Cost vs PY], [Amt Cost - PY] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ad8a64b9-30b9-4e9c-91fd-0b6fc35d4dad"
          },
          {
            "name": "Amt Cost vs PY MTD %",
            "description": "[Amt Cost vs PY] / [Amt Cost PY] | Month to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost vs PY MTD %",
              "",
              "IF (",
              "    [Amt Cost vs PY MTD] <> 0 && [Amt Cost - PY MTD] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Cost vs PY MTD], [Amt Cost - PY MTD] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "13be4cd3-9210-49b0-8df1-77d8d345ea8d"
          },
          {
            "name": "Amt Cost vs PY QTD %",
            "description": "[Amt Cost vs PY] / [Amt Cost PY] | Quarter to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost vs PY QTD %",
              "",
              "IF (",
              "    [Amt Cost vs PY QTD] <> 0 && [Amt Cost PY QTD] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Cost vs PY QTD], [Amt Cost PY QTD] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "730bdc7b-7346-4f4e-9317-b4f04b120c2a"
          },
          {
            "name": "Amt Cost vs PY YTD %",
            "description": "[Amt Cost vs PY] / [Amt Cost PY] | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost vs PY YTD %",
              "",
              "IF (",
              "    [Amt Cost vs PY YTD] <> 0 && [Amt Cost PY YTD] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Cost vs PY YTD], [Amt Cost PY YTD] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ec39ca22-e13b-49d5-8e00-4c1531949ce7"
          },
          {
            "name": "Amt Cost vs PY YTotal %",
            "description": "[Amt Cost vs PY] / [Amt Cost PY] | Total Year: Activity for entire year of specified Calendar date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost vs PY YTotal %",
              "",
              "IF (",
              "    [Amt Cost vs PY YTotal] <> 0 && [Amt Cost - PY YTotal] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Cost vs PY YTotal], [Amt Cost - PY YTotal] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "158b0e96-15e8-467a-80ab-a3cf33517a66"
          },
          {
            "name": "Amt Cost vs PY MTD",
            "description": "[Amt Cost] - [Amt Cost PY] | Month to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost vs PY MTD",
              "",
              "[Amt Cost - MTD] - [Amt Cost - PY MTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "2e82ef7b-4ee3-40d0-a10d-cf85921d8bce"
          },
          {
            "name": "Amt Cost vs PY QTD",
            "description": "[Amt Cost] - [Amt Cost PY] | Quarter to Date: Activity from beginning of quarter through specified Calendar date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost vs PY QTD",
              "",
              "[Amt Cost - QTD] - [Amt Cost PY QTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "f8764650-bef4-4fa3-b1a8-fa3a04282b12"
          },
          {
            "name": "Amt Cost vs PY YTD",
            "description": "[Amt Cost] - [Amt Cost PY] | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost vs PY YTD",
              "",
              "[Amt Cost - YTD] - [Amt Cost PY YTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "f5c45a51-85e2-4e30-9a92-5f624b2cef37"
          },
          {
            "name": "Amt Cost PY QTD",
            "description": "Amt Cost | Prior Year | Quarter to Date: Activity from beginning of quarter through specified Calendar date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost PY QTD",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "14bbc7bf-d0c5-4632-9b4f-80af70f52f29"
          },
          {
            "name": "Amt Cost PY YTD",
            "description": "Amt Cost | Prior Year | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost PY YTD",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "9e581c60-aba4-4332-8716-de31595d80d3"
          },
          {
            "name": "Amt Cost - PY YTotal",
            "description": "Amt Cost  - Year Total",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost - PY YTotal",
              "",
              "CALCULATE (",
              "    [Amt Cost_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTotal\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "1c89bd70-3c3e-4409-8d41-578b2de59bb1"
          },
          {
            "name": "Amt Cost vs PY YTotal",
            "description": "[Amt Cost] - [Amt Cost PY] | Total Year: Activity for entire year of specified Calendar date",
            "displayFolder": "Amt Cost",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost vs PY YTotal",
              "",
              "[Amt Cost - YTotal] - [Amt Cost - PY YTotal]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "454a753a-03f9-4172-8f74-ca8814fa5049"
          },
          {
            "name": "Amt Cost Ext - P01",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P01",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P1\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "8db28418-c0e9-4cee-be04-c647bd363e49"
          },
          {
            "name": "Amt Cost Ext - P02",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P02",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P2\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "c2224fc1-d406-49b5-b77c-77349b177163"
          },
          {
            "name": "Amt Cost Ext - P03",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P03",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P3\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "32acf5a4-d803-4077-9c27-38445380327e"
          },
          {
            "name": "Amt Cost Ext - P04",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P04",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P4\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "d0b01981-d1a1-41f9-97ea-42ebce8d774c"
          },
          {
            "name": "Amt Cost Ext - P05",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P05",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P5\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "38bd261b-f027-4459-9ba2-f561402d1828"
          },
          {
            "name": "Amt Cost Ext - P06",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P06",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P6\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "a200bccb-cf43-4724-8b2c-3117ac4bea94"
          },
          {
            "name": "Amt Cost Ext - P07",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P07",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P7\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "68cd5644-33b8-4a6f-808e-c92988496068"
          },
          {
            "name": "Amt Cost Ext - P08",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P08",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P8\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "b578f7c0-6f38-4a05-bc22-5f6de430aa03"
          },
          {
            "name": "Amt Cost Ext - P09",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P09",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P9\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "ef7db226-a8a4-4539-8463-68c617a7a227"
          },
          {
            "name": "Amt Cost Ext - P10",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P10",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P10\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "1c43c3c8-6400-499d-a06c-ba5a6f684962"
          },
          {
            "name": "Amt Cost Ext - P11",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P11",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P11\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "3bc77368-2cb9-49bc-aea5-36c039cc9bbb"
          },
          {
            "name": "Amt Cost Ext - P12",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P12",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P12\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "c5494210-a118-4c2d-85ec-1756f270492b"
          },
          {
            "name": "Amt Cost Ext - P13",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P13",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P13\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "992f1666-4703-4a9d-b4f2-acc02cc6341e"
          },
          {
            "name": "Amt Cost Ext - P14",
            "displayFolder": "Amt Cost Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - P14",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P14\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "b3aadf7d-d676-4376-bab6-9eccb1d6397b"
          },
          {
            "name": "Amt Cost Ext - Current",
            "description": "Amt Cost Ext - Current",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - Current",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"Current\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "38668ac8-7771-4142-ae69-0e9f0f399f17"
          },
          {
            "name": "Amt Cost Ext - ITD",
            "description": "Amt Cost Ext  - Inception to Date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - ITD",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"ITD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "a0b1e360-fb0f-4235-b5fe-eeb4f3227ae5"
          },
          {
            "name": "Amt Cost Ext - MTD",
            "description": "Amt Cost Ext  - Month to Date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - MTD",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"MTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9e027821-7c66-415e-b24f-dad1ecc6c389"
          },
          {
            "name": "Amt Cost Ext - PP",
            "description": "Amt Cost Ext  - Prior Period",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - PP",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PP\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "97aa9355-3e59-4100-ba75-efbd1de62cf3"
          },
          {
            "name": "Amt Cost Ext - PY",
            "description": "Amt Cost Ext  - Prior Year",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - PY",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "65ace4d5-cc89-45f9-a5b1-244580194b87"
          },
          {
            "name": "Amt Cost Ext - PY ITD",
            "description": "Amt Cost Ext  - Prior Year Inception to Date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - PY ITD",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY ITD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "b0c91e40-164c-4b46-9447-e3f6e4f9a402"
          },
          {
            "name": "Amt Cost Ext - PY MTD",
            "description": "Amt Cost Ext  - Prior Year Month to Date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - PY MTD",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY MTD",
              "        \"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "bb86a26e-782f-4c98-8f27-e1defdb382f2"
          },
          {
            "name": "Amt Cost Ext - PY QTD",
            "description": "Amt Cost Ext  - Prior Year Quarter to Date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - PY QTD",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "62631705-8eab-4b9c-9ed3-76ca94ce27d6"
          },
          {
            "name": "Amt Cost Ext - PY YTD",
            "description": "Amt Cost Ext  - Prior Year Year to Date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - PY YTD",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "50bf896b-4168-4032-b27f-1e32516993cb"
          },
          {
            "name": "Amt Cost Ext - QTD",
            "description": "Amt Cost Ext  - Quarter to Date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - QTD",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "510cb989-61a9-421e-95d8-7d75ba1205bc"
          },
          {
            "name": "Amt Cost Ext - YTD",
            "description": "Amt Cost Ext  - Year to Date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - YTD",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "39cac10b-e1ae-4a8b-a74a-96a94c7f4f46"
          },
          {
            "name": "Amt Cost Ext - YTotal",
            "description": "Amt Cost Ext  - Year Total",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - YTotal",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"YTotal\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "8a58e416-1102-4588-9995-a139f49ab741"
          },
          {
            "name": "Amt Cost Ext_input",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Amt Cost Ext  - Input Measure",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext_input",
              "",
              "-- I do this so later on we can add a switch for live currency conversion - Tom Sampson 20230901",
              "SUMX(Sales, Sales[OrderQuantity] * Sales[ProductStandardCost])"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "lineageTag": "6a86b4b6-236b-46f2-9fed-c1968e7dab2c"
          },
          {
            "name": "Amt Cost Ext vs PY",
            "description": "Amt Cost Ext  - Current - Prior Year",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext vs PY",
              "",
              "[Amt Cost Ext - Current] - [Amt Cost Ext - PY]"
            ],
            "formatString": "#,##0",
            "lineageTag": "26f428a7-8dfa-40f7-a7da-9e615b7a1bf8"
          },
          {
            "name": "Amt Cost Ext - Current vs PY %",
            "description": "Amt Cost Ext  - Current vs PY / PY",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - Current vs PY %",
              "",
              "DIVIDE (",
              "    [Amt Cost Ext vs PY],",
              "    [Amt Cost Ext - PY],",
              "    BLANK ( )",
              ")"
            ],
            "formatString": "#,##0 %",
            "lineageTag": "11e660c6-7e35-40b8-a1eb-5d7b34ec632e"
          },
          {
            "name": "Amt Cost Ext vs PY %",
            "description": "[Amt Cost Ext vs PY] / [Amt Cost Ext PY] ",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext vs PY %",
              "",
              "IF (",
              "    [Amt Cost Ext vs PY] <> 0 && [Amt Cost Ext - PY] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Cost Ext vs PY], [Amt Cost Ext - PY] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "9283fadb-2a2a-4633-a0c9-b0884a9831a1"
          },
          {
            "name": "Amt Cost Ext vs PY MTD %",
            "description": "[Amt Cost Ext vs PY] / [Amt Cost Ext PY] | Month to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext vs PY MTD %",
              "",
              "IF (",
              "    [Amt Cost Ext vs PY MTD] <> 0 && [Amt Cost Ext - PY MTD] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Cost Ext vs PY MTD], [Amt Cost Ext - PY MTD] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "02786da9-c6cc-49c7-9299-2a001c12b17e"
          },
          {
            "name": "Amt Cost Ext vs PY QTD %",
            "description": "[Amt Cost Ext vs PY] / [Amt Cost Ext PY] | Quarter to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext vs PY QTD %",
              "",
              "IF (",
              "    [Amt Cost Ext vs PY QTD] <> 0 && [Amt Cost Ext PY QTD] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Cost Ext vs PY QTD], [Amt Cost Ext PY QTD] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c5b27151-958a-43a4-9c74-0d7c8dcac217"
          },
          {
            "name": "Amt Cost Ext vs PY YTD %",
            "description": "[Amt Cost Ext vs PY] / [Amt Cost Ext PY] | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext vs PY YTD %",
              "",
              "IF (",
              "    [Amt Cost Ext vs PY YTD] <> 0 && [Amt Cost Ext PY YTD] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Cost Ext vs PY YTD], [Amt Cost Ext PY YTD] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "773c2096-7607-41ae-a8f1-d0b45ea33e5f"
          },
          {
            "name": "Amt Cost Ext vs PY YTotal %",
            "description": "[Amt Cost Ext vs PY] / [Amt Cost Ext PY] | Total Year: Activity for entire year of specified Calendar date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext vs PY YTotal %",
              "",
              "IF (",
              "    [Amt Cost Ext vs PY YTotal] <> 0",
              "        && [Amt Cost Ext - PY YTotal] = 0,",
              "    1,",
              "    DIVIDE (",
              "        [Amt Cost Ext vs PY YTotal],",
              "        [Amt Cost Ext - PY YTotal]",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2ac94110-71c0-4a1c-b3d6-9b155bd83222"
          },
          {
            "name": "Amt Cost Ext vs PY MTD",
            "description": "[Amt Cost Ext] - [Amt Cost Ext PY] | Month to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext vs PY MTD",
              "",
              "[Amt Cost Ext - MTD] - [Amt Cost Ext - PY MTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "2e3590d8-b66d-4bbf-8a86-9fbd52e70158"
          },
          {
            "name": "Amt Cost Ext vs PY QTD",
            "description": "[Amt Cost Ext] - [Amt Cost Ext PY] | Quarter to Date: Activity from beginning of quarter through specified Calendar date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext vs PY QTD",
              "",
              "[Amt Cost Ext - QTD] - [Amt Cost Ext PY QTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "108484b5-1626-4960-9004-d5c4a4d96799"
          },
          {
            "name": "Amt Cost Ext vs PY YTD",
            "description": "[Amt Cost Ext] - [Amt Cost Ext PY] | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext vs PY YTD",
              "",
              "[Amt Cost Ext - YTD] - [Amt Cost Ext PY YTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "398f8715-d403-4aa7-8abb-396c2a961591"
          },
          {
            "name": "Amt Cost Ext PY QTD",
            "description": "Amt Cost Ext | Prior Year | Quarter to Date: Activity from beginning of quarter through specified Calendar date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext PY QTD",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "06fc5f2b-d65e-4be9-b741-b21b3d08ae58"
          },
          {
            "name": "Amt Cost Ext PY YTD",
            "description": "Amt Cost Ext | Prior Year | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext PY YTD",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "1f71a802-6384-4bdc-b1ef-1c6c15e4ef18"
          },
          {
            "name": "Amt Cost Ext - PY YTotal",
            "description": "Amt Cost Ext  - Year Total",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext - PY YTotal",
              "",
              "CALCULATE (",
              "    [Amt Cost Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTotal\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "5b342782-1bf3-4202-8441-31ae4ef6d7ae"
          },
          {
            "name": "Amt Cost Ext vs PY YTotal",
            "description": "[Amt Cost Ext] - [Amt Cost Ext PY] | Total Year: Activity for entire year of specified Calendar date",
            "displayFolder": "Amt Cost Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Cost Ext vs PY YTotal",
              "",
              "[Amt Cost Ext - YTotal] - [Amt Cost Ext - PY YTotal]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8ad8f69a-f02e-453b-b0c9-043544775807"
          },
          {
            "name": "Amt Sales - P01",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P01",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P1\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "d365857e-bf9c-4d00-b465-dfb1f2d05ba7"
          },
          {
            "name": "Amt Sales - P02",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P02",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P2\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "aed8a194-724a-44d9-b1d3-d23b2b0315fe"
          },
          {
            "name": "Amt Sales - P03",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P03",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P3\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "76f49451-f0bb-497e-b336-6ba8f563cc4a"
          },
          {
            "name": "Amt Sales - P04",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P04",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P4\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "8b054096-6a82-43f6-8f51-3f91e4c79280"
          },
          {
            "name": "Amt Sales - P05",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P05",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P5\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "16e23bbc-117b-47c2-ae09-d57714bacb6c"
          },
          {
            "name": "Amt Sales - P06",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P06",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P6\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "83d3272b-5b9a-4c49-b200-455da20050fa"
          },
          {
            "name": "Amt Sales - P07",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P07",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P7\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "00c708b8-438a-46e9-a535-269dbde534fa"
          },
          {
            "name": "Amt Sales - P08",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P08",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P8\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "1f7a7051-077c-4fb9-a16f-3ebfeef7fac9"
          },
          {
            "name": "Amt Sales - P09",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P09",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P9\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "141b73f1-ba34-4e64-905f-a632132636df"
          },
          {
            "name": "Amt Sales - P10",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P10",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P10\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "14df2b0e-991a-4dcb-ab04-aa44e6bb9c04"
          },
          {
            "name": "Amt Sales - P11",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P11",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P11\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "bb1bb6d0-6be7-4c96-b089-058a6dc01ffd"
          },
          {
            "name": "Amt Sales - P12",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P12",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P12\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "79f88ce9-91d6-44f3-ba4e-c861565a2326"
          },
          {
            "name": "Amt Sales - P13",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P13",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P13\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "4f7867ee-83ba-4d25-9f13-46ee700d78d8"
          },
          {
            "name": "Amt Sales - P14",
            "displayFolder": "Amt Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - P14",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P14\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "153cc381-0305-4be0-b46c-54f4a17b8e19"
          },
          {
            "name": "Amt Sales - Current",
            "description": "Amt Sales - Current",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - Current",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"Current\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "0898966c-5636-458a-9d7e-36409f8ad856"
          },
          {
            "name": "Amt Sales - ITD",
            "description": "Amt Sales  - Inception to Date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - ITD",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"ITD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "e9b2d7a4-523c-48e5-9622-a6e54c8069e5"
          },
          {
            "name": "Amt Sales - MTD",
            "description": "Amt Sales  - Month to Date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - MTD",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"MTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "89036267-d62e-4288-ae10-9aef007230e5"
          },
          {
            "name": "Amt Sales - PP",
            "description": "Amt Sales  - Prior Period",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - PP",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PP\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "8d84e595-cdd6-4741-9172-ed89bab06500"
          },
          {
            "name": "Amt Sales - PY",
            "description": "Amt Sales  - Prior Year",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - PY",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "5c22e362-102a-450f-9be5-4317a9c2a463"
          },
          {
            "name": "Amt Sales - PY ITD",
            "description": "Amt Sales  - Prior Year Inception to Date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - PY ITD",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY ITD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "cd59aac1-420e-4d43-91f1-7893c4fa86ac"
          },
          {
            "name": "Amt Sales - PY MTD",
            "description": "Amt Sales  - Prior Year Month to Date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - PY MTD",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY MTD",
              "        \"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "e3183f66-5114-41bc-a26e-682e0152eec9"
          },
          {
            "name": "Amt Sales - PY QTD",
            "description": "Amt Sales  - Prior Year Quarter to Date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - PY QTD",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "c381b789-e77f-4988-bcdd-d7b189ef4c6c"
          },
          {
            "name": "Amt Sales - PY YTD",
            "description": "Amt Sales  - Prior Year Year to Date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - PY YTD",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "02ad4c98-9fc0-4a28-8062-6dd7b755fb5a"
          },
          {
            "name": "Amt Sales - QTD",
            "description": "Amt Sales  - Quarter to Date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - QTD",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "39a5e57b-c9ac-4375-ab4a-7d838d77ab81"
          },
          {
            "name": "Amt Sales - YTD",
            "description": "Amt Sales  - Year to Date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - YTD",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "e207aae1-27c2-47f7-87cf-2e07ca182ae8"
          },
          {
            "name": "Amt Sales - YTotal",
            "description": "Amt Sales  - Year Total",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - YTotal",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"YTotal\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "f1c69014-2877-4e19-865b-263f9119ab6b"
          },
          {
            "name": "Amt Sales_input",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Amt Sales  - Input Measure",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales_input",
              "",
              "-- I do this so later on we can add a switch for live currency conversion - Tom Sampson 20230901",
              "SUM ( Sales[SalesAmount] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "lineageTag": "c2ee4123-6d15-480e-9a42-b9e9401099d8"
          },
          {
            "name": "Amt Sales vs PY",
            "description": "Amt Sales  - Current - Prior Year",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales vs PY",
              "",
              "[Amt Sales - Current] - [Amt Sales - PY]"
            ],
            "formatString": "#,##0",
            "lineageTag": "006f04ef-768b-4758-b096-abd5a5b5769c"
          },
          {
            "name": "Amt Sales - Current vs PY %",
            "description": "Amt Sales  - Current vs PY / PY",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - Current vs PY %",
              "",
              "DIVIDE ( [Amt Sales vs PY], [Amt Sales - PY], BLANK ( ) )"
            ],
            "formatString": "#,##0 %",
            "lineageTag": "57e950fa-9ef0-41a5-9ba8-6f2626bbf16e"
          },
          {
            "name": "Amt Sales vs PY %",
            "description": "[Amt Sales vs PY] / [Amt Sales PY] ",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales vs PY %",
              "",
              "IF (",
              "    [Amt Sales vs PY] <> 0 && [Amt Sales - PY] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Sales vs PY], [Amt Sales - PY] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e947c64d-0c12-4763-8c35-c0a962e4831a"
          },
          {
            "name": "Amt Sales vs PY MTD %",
            "description": "[Amt Sales vs PY] / [Amt Sales PY] | Month to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales vs PY MTD %",
              "",
              "IF (",
              "    [Amt Sales vs PY MTD] <> 0 && [Amt Sales - PY MTD] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Sales vs PY MTD], [Amt Sales - PY MTD] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "827ba4b3-670e-4dcd-a4ae-c52cf289a2ef"
          },
          {
            "name": "Amt Sales vs PY QTD %",
            "description": "[Amt Sales vs PY] / [Amt Sales PY] | Quarter to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales vs PY QTD %",
              "",
              "IF (",
              "    [Amt Sales vs PY QTD] <> 0 && [Amt Sales PY QTD] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Sales vs PY QTD], [Amt Sales PY QTD] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d432bdd0-a97e-472c-9583-0acbed3bbb4e"
          },
          {
            "name": "Amt Sales vs PY YTD %",
            "description": "[Amt Sales vs PY] / [Amt Sales PY] | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales vs PY YTD %",
              "",
              "IF (",
              "    [Amt Sales vs PY YTD] <> 0 && [Amt Sales PY YTD] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Sales vs PY YTD], [Amt Sales PY YTD] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "915cf3a6-f5cb-4f12-98a5-1aa9b0781da0"
          },
          {
            "name": "Amt Sales vs PY YTotal %",
            "description": "[Amt Sales vs PY] / [Amt Sales PY] | Total Year: Activity for entire year of specified Calendar date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales vs PY YTotal %",
              "",
              "IF (",
              "    [Amt Sales vs PY YTotal] <> 0 && [Amt Sales - PY YTotal] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Sales vs PY YTotal], [Amt Sales - PY YTotal] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "159bb6d9-327f-474a-8345-9ca63e05a3d3"
          },
          {
            "name": "Amt Sales vs PY MTD",
            "description": "[Amt Sales] - [Amt Sales PY] | Month to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales vs PY MTD",
              "",
              "[Amt Sales - MTD] - [Amt Sales - PY MTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "59800706-e84d-4fe4-a911-f6ba2031fe2a"
          },
          {
            "name": "Amt Sales vs PY QTD",
            "description": "[Amt Sales] - [Amt Sales PY] | Quarter to Date: Activity from beginning of quarter through specified Calendar date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales vs PY QTD",
              "",
              "[Amt Sales - QTD] - [Amt Sales PY QTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "518aa3ac-008d-46fd-9b17-dee797e5757e"
          },
          {
            "name": "Amt Sales vs PY YTD",
            "description": "[Amt Sales] - [Amt Sales PY] | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales vs PY YTD",
              "",
              "[Amt Sales - YTD] - [Amt Sales PY YTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "739d0ae8-fc76-4f30-a1f6-f4080563281a"
          },
          {
            "name": "Amt Sales PY QTD",
            "description": "Amt Sales | Prior Year | Quarter to Date: Activity from beginning of quarter through specified Calendar date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales PY QTD",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "0d827cbe-8013-4c94-ae68-9e0c9e767059"
          },
          {
            "name": "Amt Sales PY YTD",
            "description": "Amt Sales | Prior Year | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales PY YTD",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "47cbeabb-69aa-4b11-acf1-c8c9f3dedfaa"
          },
          {
            "name": "Amt Sales - PY YTotal",
            "description": "Amt Sales  - Year Total",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - PY YTotal",
              "",
              "CALCULATE (",
              "    [Amt Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTotal\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "0d837d41-e87d-4d2e-958f-b3aa2f5d7c6d"
          },
          {
            "name": "Amt Sales vs PY YTotal",
            "description": "[Amt Sales] - [Amt Sales PY] | Total Year: Activity for entire year of specified Calendar date",
            "displayFolder": "Amt Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales vs PY YTotal",
              "",
              "[Amt Sales - YTotal] - [Amt Sales - PY YTotal]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "60ccd9bd-e52b-4bb9-96bf-fc78f02992da"
          },
          {
            "name": "Amt Sales - Current (RF)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Amt Sales\\Country",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales - Current (RF)",
              "",
              "VAR AmtSalesCurrentRF =",
              "    CALCULATE (",
              "        [Amt Sales - Current],",
              "        REMOVEFILTERS ( Sales[Country] )",
              "    )",
              "RETURN",
              "    AmtSalesCurrentRF"
            ],
            "lineageTag": "9558ffd4-161a-4460-ae5e-7f172e3c6cbd"
          },
          {
            "name": "% Amt Sales (RF)",
            "displayFolder": "Amt Sales\\Country",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - % Amt Sales (RF)",
              "",
              "VAR AmtSalesRF =",
              "    CALCULATE (",
              "        [Amt Sales - Current],",
              "        REMOVEFILTERS ( Sales[Country] )",
              "    )",
              "VAR Ratio = DIVIDE ( [Amt Sales - Current], AmtSalesRF )",
              "RETURN",
              "    Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "23bdab12-17d9-4811-9a91-05e3a9317613"
          },
          {
            "name": "Amt Sales Ext - P01",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P01",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P1\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "077268a2-8b6e-4852-bf85-f6b375f06df3"
          },
          {
            "name": "Amt Sales Ext - P02",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P02",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P2\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9bce0422-c4b1-43dd-acfa-34b614da9c0e"
          },
          {
            "name": "Amt Sales Ext - P03",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P03",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P3\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "42ccda57-8ada-4dee-96b3-2623c6f4065a"
          },
          {
            "name": "Amt Sales Ext - P04",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P04",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P4\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "7618d457-c39c-4127-9c7c-69a36756b8ee"
          },
          {
            "name": "Amt Sales Ext - P05",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P05",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P5\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "babb7360-9639-4a54-a1b3-52dc3d4c904f"
          },
          {
            "name": "Amt Sales Ext - P06",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P06",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P6\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "5d037392-c07f-4955-8814-8685f4d2d202"
          },
          {
            "name": "Amt Sales Ext - P07",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P07",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P7\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "da63963d-112c-450a-af16-208d084aa607"
          },
          {
            "name": "Amt Sales Ext - P08",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P08",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P8\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "e6354499-ef62-4121-84db-622dfc8780f5"
          },
          {
            "name": "Amt Sales Ext - P09",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P09",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P9\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "b681ea89-f0e6-48cf-9110-8f317c2b0480"
          },
          {
            "name": "Amt Sales Ext - P10",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P10",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P10\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "5b204467-01c9-4d06-96a0-3b93a283b0b7"
          },
          {
            "name": "Amt Sales Ext - P11",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P11",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P11\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "53836fcb-f476-484d-983e-3935a1b91d8b"
          },
          {
            "name": "Amt Sales Ext - P12",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P12",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P12\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "d11ef2de-b73d-46b5-956b-6f1cefe30971"
          },
          {
            "name": "Amt Sales Ext - P13",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P13",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P13\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "b7f7cbe1-c5bd-40dc-b41e-37a4f724e88b"
          },
          {
            "name": "Amt Sales Ext - P14",
            "displayFolder": "Amt Sales Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - P14",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P14\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "b83d7ccd-ea70-458c-b27d-ceca1e68cfe7"
          },
          {
            "name": "Amt Sales Ext - Current",
            "description": "Amt Sales Ext - Current",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - Current",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"Current\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "08a369d5-770c-47c3-a5e8-c20c9c7db4f2"
          },
          {
            "name": "Amt Sales Ext - ITD",
            "description": "Amt Sales Ext  - Inception to Date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - ITD",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"ITD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "e56c974e-5290-4234-b14c-a50c4fa3d82a"
          },
          {
            "name": "Amt Sales Ext - MTD",
            "description": "Amt Sales Ext  - Month to Date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - MTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"MTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "7ca141e0-64af-434f-a97b-aa0707a14ea6"
          },
          {
            "name": "Amt Sales Ext - PP",
            "description": "Amt Sales Ext  - Prior Period",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - PP",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PP\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "48b57293-b253-41a0-9bab-9d4b5e3192b0"
          },
          {
            "name": "Amt Sales Ext - PY",
            "description": "Amt Sales Ext  - Prior Year",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - PY",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "1987819f-deff-4bd0-8b59-cc1c1fa521f8"
          },
          {
            "name": "Amt Sales Ext - PY ITD",
            "description": "Amt Sales Ext  - Prior Year Inception to Date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - PY ITD",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY ITD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "1576f090-f1fa-48de-923b-545656177d4d"
          },
          {
            "name": "Amt Sales Ext - PY MTD",
            "description": "Amt Sales Ext  - Prior Year Month to Date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - PY MTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY MTD",
              "        \"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9009ae3f-4336-4e95-a912-1f5939362424"
          },
          {
            "name": "Amt Sales Ext - PY QTD",
            "description": "Amt Sales Ext  - Prior Year Quarter to Date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - PY QTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "80aea60f-3d6c-4a38-92be-a9257d68e7f6"
          },
          {
            "name": "Amt Sales Ext - PY YTD",
            "description": "Amt Sales Ext  - Prior Year Year to Date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - PY YTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "36fa7be3-d561-4d25-9af2-2ff716bb34ba"
          },
          {
            "name": "Amt Sales Ext - QTD",
            "description": "Amt Sales Ext  - Quarter to Date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - QTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "b6fd6566-4891-4dea-9049-a1b27742348e"
          },
          {
            "name": "Amt Sales Ext - YTD",
            "description": "Amt Sales Ext  - Year to Date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - YTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "70ae187f-72e2-4cc5-8417-7d81f7ceb3fe"
          },
          {
            "name": "Amt Sales Ext - YTotal",
            "description": "Amt Sales Ext  - Year Total",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - YTotal",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"YTotal\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "cc08c9d5-d287-41d6-8ba2-fc5e598f39ac"
          },
          {
            "name": "Amt Sales Ext_input",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Amt Sales Ext  - Input Measure",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext_input",
              "",
              "-- I do this so later on we can add a switch for live currency conversion - Tom Sampson 20230901",
              "SUMX(Sales, Sales[OrderQuantity] * Sales[SalesAmount])"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "lineageTag": "6ffdf8ae-fd19-4092-bba9-cc6ae17c7c2c"
          },
          {
            "name": "Amt Sales Ext vs PY",
            "description": "Amt Sales Ext  - Current - Prior Year",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext vs PY",
              "",
              "[Amt Sales Ext - Current] - [Amt Sales Ext - PY]"
            ],
            "formatString": "#,##0",
            "lineageTag": "51e50555-aa23-491b-b9ed-d240661f7c06"
          },
          {
            "name": "Amt Sales Ext - Current vs PY %",
            "description": "Amt Sales Ext  - Current vs PY / PY",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - Current vs PY %",
              "",
              "DIVIDE (",
              "    [Amt Sales Ext vs PY],",
              "    [Amt Sales Ext - PY],",
              "    BLANK ( )",
              ")"
            ],
            "formatString": "#,##0 %",
            "lineageTag": "55023beb-7e55-4ed5-8f1e-b535c18bf7c0"
          },
          {
            "name": "Amt Sales Ext vs PY %",
            "description": "[Amt Sales Ext vs PY] / [Amt Sales Ext PY] ",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext vs PY %",
              "",
              "IF (",
              "    [Amt Sales Ext vs PY] <> 0 && [Amt Sales Ext - PY] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Sales Ext vs PY], [Amt Sales Ext - PY] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4ca34600-b1da-4a45-9e8f-fb8dfa0b6206"
          },
          {
            "name": "Amt Sales Ext vs PY MTD %",
            "description": "[Amt Sales Ext vs PY] / [Amt Sales Ext PY] | Month to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext vs PY MTD %",
              "",
              "IF (",
              "    [Amt Sales Ext vs PY MTD] <> 0 && [Amt Sales Ext - PY MTD] = 0,",
              "    1,",
              "    DIVIDE (",
              "        [Amt Sales Ext vs PY MTD],",
              "        [Amt Sales Ext - PY MTD]",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8315483b-48b1-4aea-a6b9-dc164ccbfefd"
          },
          {
            "name": "Amt Sales Ext vs PY QTD %",
            "description": "[Amt Sales Ext vs PY] / [Amt Sales Ext PY] | Quarter to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext vs PY QTD %",
              "",
              "IF (",
              "    [Amt Sales Ext vs PY QTD] <> 0 && [Amt Sales Ext PY QTD] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Sales Ext vs PY QTD], [Amt Sales Ext PY QTD] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "86417c29-6b4b-4e38-bc52-7fd0ba534b6f"
          },
          {
            "name": "Amt Sales Ext vs PY YTD %",
            "description": "[Amt Sales Ext vs PY] / [Amt Sales Ext PY] | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext vs PY YTD %",
              "",
              "IF (",
              "    [Amt Sales Ext vs PY YTD] <> 0 && [Amt Sales Ext PY YTD] = 0,",
              "    1,",
              "    DIVIDE ( [Amt Sales Ext vs PY YTD], [Amt Sales Ext PY YTD] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f6d41687-e30e-44ea-b1e2-932248d511be"
          },
          {
            "name": "Amt Sales Ext vs PY YTotal %",
            "description": "[Amt Sales Ext vs PY] / [Amt Sales Ext PY] | Total Year: Activity for entire year of specified Calendar date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext vs PY YTotal %",
              "",
              "IF (",
              "    [Amt Sales Ext vs PY YTotal] <> 0",
              "        && [Amt Sales Ext - PY YTotal] = 0,",
              "    1,",
              "    DIVIDE (",
              "        [Amt Sales Ext vs PY YTotal],",
              "        [Amt Sales Ext - PY YTotal]",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a1f94b02-6ccb-42d7-84e3-36b3f56f341c"
          },
          {
            "name": "Amt Sales Ext vs PY MTD",
            "description": "[Amt Sales Ext] - [Amt Sales Ext PY] | Month to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext vs PY MTD",
              "",
              "[Amt Sales Ext - MTD] - [Amt Sales Ext - PY MTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "3752bedf-0446-4855-a1fd-93fa157dacce"
          },
          {
            "name": "Amt Sales Ext vs PY QTD",
            "description": "[Amt Sales Ext] - [Amt Sales Ext PY] | Quarter to Date: Activity from beginning of quarter through specified Calendar date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext vs PY QTD",
              "",
              "[Amt Sales Ext - QTD] - [Amt Sales Ext PY QTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "93316e6a-1606-455b-9e39-bc45e18c851a"
          },
          {
            "name": "Amt Sales Ext vs PY YTD",
            "description": "[Amt Sales Ext] - [Amt Sales Ext PY] | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext vs PY YTD",
              "",
              "[Amt Sales Ext - YTD] - [Amt Sales Ext PY YTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "a82b518f-ea26-4554-a0b6-adbb317bc6e4"
          },
          {
            "name": "Amt Sales Ext PY QTD",
            "description": "Amt Sales Ext | Prior Year | Quarter to Date: Activity from beginning of quarter through specified Calendar date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext PY QTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "d47a5e3c-afcf-4402-896b-e855492ca0e5"
          },
          {
            "name": "Amt Sales Ext PY YTD",
            "description": "Amt Sales Ext | Prior Year | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext PY YTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "d412d0c6-0ba4-4c71-bf25-8c00285572e3"
          },
          {
            "name": "Amt Sales Ext - PY YTotal",
            "description": "Amt Sales Ext  - Year Total",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext - PY YTotal",
              "",
              "CALCULATE (",
              "    [Amt Sales Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTotal\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "1d435e4a-22f4-4b6f-8683-3d2471617e04"
          },
          {
            "name": "Amt Sales Ext vs PY YTotal",
            "description": "[Amt Sales Ext] - [Amt Sales Ext PY] | Total Year: Activity for entire year of specified Calendar date",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext vs PY YTotal",
              "",
              "[Amt Sales Ext - YTotal] - [Amt Sales Ext - PY YTotal]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e47813c1-7ec4-4c78-bf4e-2f2711ddd493"
          },
          {
            "name": "Amt Sales Profit Ext - P01",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P01",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P1\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "ebdb4a26-dfe7-4a6d-bb2e-66a58a564dc2"
          },
          {
            "name": "Amt Sales Profit Ext - P02",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P02",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P2\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "fa4c1c2d-69fd-4819-bd25-1897656628ef"
          },
          {
            "name": "Amt Sales Profit Ext - P03",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P03",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P3\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "f97590c5-015a-4e43-af9e-04b176a9c21b"
          },
          {
            "name": "Amt Sales Profit Ext - P04",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P04",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P4\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "de90e9e8-caa7-40e2-84ba-67745073d943"
          },
          {
            "name": "Amt Sales Profit Ext - P05",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P05",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P5\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9d83ad8d-7313-4a8d-9748-2a0d9c8bcf52"
          },
          {
            "name": "Amt Sales Profit Ext - P06",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P06",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P6\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "a3d01917-cb18-46e7-a4d8-1d6082f566ff"
          },
          {
            "name": "Amt Sales Profit Ext - P07",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P07",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P7\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "b4f23012-2b17-48b5-8390-e47f2d937171"
          },
          {
            "name": "Amt Sales Profit Ext - P08",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P08",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P8\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "5a2b5c94-44fd-47b1-8706-29220755ed9c"
          },
          {
            "name": "Amt Sales Profit Ext - P09",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P09",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P9\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "4dcf44aa-9c87-4410-a961-bd8c4006b4ac"
          },
          {
            "name": "Amt Sales Profit Ext - P10",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P10",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P10\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "a1047793-436f-427a-8f43-011f25884b15"
          },
          {
            "name": "Amt Sales Profit Ext - P11",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P11",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P11\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "b1c3cb51-5e70-4ea1-bd49-0371e53f1050"
          },
          {
            "name": "Amt Sales Profit Ext - P12",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P12",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P12\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9ed239a7-3e0a-49bf-881a-6f57ea57a31d"
          },
          {
            "name": "Amt Sales Profit Ext - P13",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P13",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P13\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "5616d7da-87bd-494b-a62b-4b1024158ad6"
          },
          {
            "name": "Amt Sales Profit Ext - P14",
            "displayFolder": "Amt Sales Profit Ext\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - P14",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P14\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "26cf0b83-5c8f-4dd5-ae90-24fc83d7dedc"
          },
          {
            "name": "Amt Sales Profit Ext - Current",
            "description": "Amt Sales Profit Ext - Current",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - Current",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"Current\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "d977dc45-35ce-4134-aeaa-d164572d8063"
          },
          {
            "name": "Amt Sales Profit Ext - ITD",
            "description": "Amt Sales Profit Ext  - Inception to Date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - ITD",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"ITD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "d940a3ac-1f8b-4926-935e-25e4d518c9d8"
          },
          {
            "name": "Amt Sales Profit Ext - MTD",
            "description": "Amt Sales Profit Ext  - Month to Date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - MTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"MTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "d6e081cc-36e9-4837-8fb3-00f454ca1537"
          },
          {
            "name": "Amt Sales Profit Ext - PP",
            "description": "Amt Sales Profit Ext  - Prior Period",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - PP",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PP\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "94296923-8471-427f-8b45-ca78ec1be80a"
          },
          {
            "name": "Amt Sales Profit Ext - PY",
            "description": "Amt Sales Profit Ext  - Prior Year",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - PY",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "98cd9199-b9a8-4486-a2f1-0b983c3f1a62"
          },
          {
            "name": "Amt Sales Profit Ext - PY ITD",
            "description": "Amt Sales Profit Ext  - Prior Year Inception to Date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - PY ITD",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY ITD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "3b752415-4ee9-40bd-a07f-efd6bd646092"
          },
          {
            "name": "Amt Sales Profit Ext - PY MTD",
            "description": "Amt Sales Profit Ext  - Prior Year Month to Date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - PY MTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY MTD",
              "        \"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "ed28197c-8606-440a-893c-ca6638752eee"
          },
          {
            "name": "Amt Sales Profit Ext - PY QTD",
            "description": "Amt Sales Profit Ext  - Prior Year Quarter to Date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - PY QTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9d190d4b-97dd-42cc-a71c-43378bbb2b2e"
          },
          {
            "name": "Amt Sales Profit Ext - PY YTD",
            "description": "Amt Sales Profit Ext  - Prior Year Year to Date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - PY YTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "f51e7cd5-1b08-4d93-8d0c-da9a4b409c6f"
          },
          {
            "name": "Amt Sales Profit Ext - QTD",
            "description": "Amt Sales Profit Ext  - Quarter to Date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - QTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "891eca3b-4db3-473f-a697-09ac50363c57"
          },
          {
            "name": "Amt Sales Profit Ext - YTD",
            "description": "Amt Sales Profit Ext  - Year to Date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - YTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "a2866935-6da6-42e7-a023-b10645b3c5b2"
          },
          {
            "name": "Amt Sales Profit Ext - YTotal",
            "description": "Amt Sales Profit Ext  - Year Total",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - YTotal",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"YTotal\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9a86faad-1cae-438a-a291-2fceb8bcb5d2"
          },
          {
            "name": "Amt Sales Profit Ext_input",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Amt Sales Profit Ext  - Input Measure",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext_input",
              "",
              "-- I do this so later on we can add a switch for live currency conversion - Tom Sampson 20230901",
              "[Amt Sales Ext_input] - [Amt Cost Ext_input]"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "lineageTag": "4314812e-0d7b-4024-bec4-ae0ea5ec4ee2"
          },
          {
            "name": "Amt Sales Profit Ext vs PY",
            "description": "Amt Sales Profit Ext  - Current - Prior Year",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext vs PY",
              "",
              "[Amt Sales Profit Ext - Current]",
              "    - [Amt Sales Profit Ext - PY]"
            ],
            "formatString": "#,##0",
            "lineageTag": "481454a8-bf3f-4b75-886b-3e037859f9c4"
          },
          {
            "name": "Amt Sales Profit Ext - Current vs PY %",
            "description": "Amt Sales Profit Ext  - Current vs PY / PY",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - Current vs PY %",
              "",
              "DIVIDE (",
              "    [Amt Sales Profit Ext vs PY],",
              "    [Amt Sales Profit Ext - PY],",
              "    BLANK ( )",
              ")"
            ],
            "formatString": "#,##0 %",
            "lineageTag": "cbbe40c3-9a4e-4ea8-867a-fb196555f718"
          },
          {
            "name": "Amt Sales Profit Ext vs PY %",
            "description": "[Amt Sales Profit Ext vs PY] / [Amt Sales Profit Ext PY] ",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext vs PY %",
              "",
              "IF (",
              "    [Amt Sales Profit Ext vs PY] <> 0",
              "        && [Amt Sales Profit Ext - PY] = 0,",
              "    1,",
              "    DIVIDE (",
              "        [Amt Sales Profit Ext vs PY],",
              "        [Amt Sales Profit Ext - PY]",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "492da3e3-31b0-4af4-80d3-57cc2a1bb07e"
          },
          {
            "name": "Amt Sales Profit Ext vs PY MTD %",
            "description": "[Amt Sales Profit Ext vs PY] / [Amt Sales Profit Ext PY] | Month to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext vs PY MTD %",
              "",
              "IF (",
              "    [Amt Sales Profit Ext vs PY MTD] <> 0",
              "        && [Amt Sales Profit Ext - PY MTD] = 0,",
              "    1,",
              "    DIVIDE (",
              "        [Amt Sales Profit Ext vs PY MTD],",
              "        [Amt Sales Profit Ext - PY MTD]",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b77e7602-797c-4c79-a104-84a6d151ea92"
          },
          {
            "name": "Amt Sales Profit Ext vs PY QTD %",
            "description": "[Amt Sales Profit Ext vs PY] / [Amt Sales Profit Ext PY] | Quarter to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext vs PY QTD %",
              "",
              "IF (",
              "    [Amt Sales Profit Ext vs PY QTD] <> 0",
              "        && [Amt Sales Profit Ext PY QTD] = 0,",
              "    1,",
              "    DIVIDE (",
              "        [Amt Sales Profit Ext vs PY QTD],",
              "        [Amt Sales Profit Ext PY QTD]",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "85711b26-1a15-413b-a0c6-a61e2e2016e9"
          },
          {
            "name": "Amt Sales Profit Ext vs PY YTD %",
            "description": "[Amt Sales Profit Ext vs PY] / [Amt Sales Profit Ext PY] | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext vs PY YTD %",
              "",
              "IF (",
              "    [Amt Sales Profit Ext vs PY YTD] <> 0",
              "        && [Amt Sales Profit Ext PY YTD] = 0,",
              "    1,",
              "    DIVIDE (",
              "        [Amt Sales Profit Ext vs PY YTD],",
              "        [Amt Sales Profit Ext PY YTD]",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "cee86578-a343-47aa-b5a7-6d7a7fce70bc"
          },
          {
            "name": "Amt Sales Profit Ext vs PY YTotal %",
            "description": "[Amt Sales Profit Ext vs PY] / [Amt Sales Profit Ext PY] | Total Year: Activity for entire year of specified Calendar date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext vs PY YTotal %",
              "",
              "IF (",
              "    [Amt Sales Profit Ext vs PY YTotal] <> 0",
              "        && [Amt Sales Profit Ext - PY YTotal] = 0,",
              "    1,",
              "    DIVIDE (",
              "        [Amt Sales Profit Ext vs PY YTotal],",
              "        [Amt Sales Profit Ext - PY YTotal]",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a453cb4d-6fb2-4346-8982-adcbd2460493"
          },
          {
            "name": "Amt Sales Profit Ext vs PY MTD",
            "description": "[Amt Sales Profit Ext] - [Amt Sales Profit Ext PY] | Month to Date: Activity from beginning of period through specified Calendar date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext vs PY MTD",
              "",
              "[Amt Sales Profit Ext - MTD]",
              "    - [Amt Sales Profit Ext - PY MTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "25bc3eb0-798a-458d-9afa-9a03fbe76d11"
          },
          {
            "name": "Amt Sales Profit Ext vs PY QTD",
            "description": "[Amt Sales Profit Ext] - [Amt Sales Profit Ext PY] | Quarter to Date: Activity from beginning of quarter through specified Calendar date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext vs PY QTD",
              "",
              "[Amt Sales Profit Ext - QTD] - [Amt Sales Profit Ext PY QTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "f86b755c-3ce9-4eec-bc95-d3ea49db99cb"
          },
          {
            "name": "Amt Sales Profit Ext vs PY YTD",
            "description": "[Amt Sales Profit Ext] - [Amt Sales Profit Ext PY] | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext vs PY YTD",
              "",
              "[Amt Sales Profit Ext - YTD] - [Amt Sales Profit Ext PY YTD]"
            ],
            "formatString": "#,0",
            "lineageTag": "f4547e88-a64f-42df-9201-b8bb7ef4e2c0"
          },
          {
            "name": "Amt Sales Profit Ext PY QTD",
            "description": "Amt Sales Profit Ext | Prior Year | Quarter to Date: Activity from beginning of quarter through specified Calendar date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext PY QTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "8aaeda89-175e-41f5-8ccb-0cee8df479e0"
          },
          {
            "name": "Amt Sales Profit Ext PY YTD",
            "description": "Amt Sales Profit Ext | Prior Year | Year to Date: Activity from beginning of year through specified Calendar date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext PY YTD",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "ba9f9627-11e8-41db-a1a0-9e006399ec22"
          },
          {
            "name": "Amt Sales Profit Ext - PY YTotal",
            "description": "Amt Sales Profit Ext  - Year Total",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext - PY YTotal",
              "",
              "CALCULATE (",
              "    [Amt Sales Profit Ext_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTotal\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "c8ac2e5b-1f84-42e0-92b9-70b532766c93"
          },
          {
            "name": "Amt Sales Profit Ext vs PY YTotal",
            "description": "[Amt Sales Profit Ext] - [Amt Sales Profit Ext PY] | Total Year: Activity for entire year of specified Calendar date",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Profit Ext vs PY YTotal",
              "",
              "[Amt Sales Profit Ext - YTotal]",
              "    - [Amt Sales Profit Ext - PY YTotal]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e8148acf-74f2-409a-a1fd-3acfd4fd7089"
          },
          {
            "name": "Profit Percentage by Color, SubCategory, and Category - Current",
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Profit Percentage by Color, SubCategory, and Category - Current",
              "",
              "DIVIDE (",
              "    [Amt Sales Profit Ext - Current],",
              "    CALCULATE (",
              "        [Amt Sales Profit Ext - Current],",
              "        ALL ( Products )",
              "    )",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7cadafcb-945e-48d9-939a-062e279272f9"
          },
          {
            "name": "Total Profit - Current",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Amt Sales Profit Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Total Profit - Current",
              "",
              "SUMX ( Products, [Amt Sales Profit Ext - Current] )"
            ],
            "lineageTag": "f5447f3d-477a-4842-992c-2a8754ce34e0"
          },
          {
            "name": "Rank Profit by Product",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Calculations",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Rank Profit by Product",
              "",
              "IF (",
              "    HASONEVALUE ( Products[Product ID & Desc] ),",
              "    RANKX (",
              "        ALLSELECTED ( Products[Product ID & Desc] ),",
              "        [Amt Sales Profit Ext - Current],",
              "        ,",
              "        DESC,",
              "        DENSE",
              "    )",
              ")"
            ],
            "lineageTag": "9bcdadd1-d191-4ef7-baf3-85ac7448ce31"
          },
          {
            "name": "Distinct Count Sales Orders",
            "displayFolder": "Calculations",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Distinct Count Sales Orders",
              "",
              "DISTINCTCOUNT ( Sales[OrderKey] )"
            ],
            "formatString": "#,0",
            "lineageTag": "53343283-941f-42cf-adcd-5cf17d757087"
          },
          {
            "name": "Amt Best Day",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Calculations",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Best Day",
              "",
              "VAR TopDay =",
              "    TOPN (",
              "        1,",
              "        VALUES ( Calendar[CalendarDate] ),",
              "        [Amt Sales - Current], DESC",
              "    )",
              "RETURN",
              "    MAXX ( TopDay, [Amt Sales - Current] )"
            ],
            "lineageTag": "3302d3cc-5b61-4712-9023-7b1500390c0b"
          },
          {
            "name": "Best Day",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Calculations",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Best Day",
              "",
              "VAR TopDay =",
              "    TOPN (",
              "        1,",
              "        VALUES ( Calendar[CalendarDate] ),",
              "        [Amt Sales - Current], DESC",
              "    )",
              "RETURN",
              "    FORMAT ( MAXX ( TopDay, Calendar[CalendarDate] ), \"m/d/yy\" )"
            ],
            "lineageTag": "3f5bd04c-b403-4de6-bb59-2fd0c1619d68"
          },
          {
            "name": "MinOrderDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Calculations",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - MinOrderDate",
              "",
              "FORMAT ( MIN ( Sales[OrderDate] ), \"yyyy-mm-dd\" )"
            ],
            "lineageTag": "6ea21158-4161-426a-b5f5-924c3721f228"
          },
          {
            "name": "MaxOrderDate",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Calculations",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - MaxOrderDate",
              "",
              "FORMAT ( MAX ( Sales[OrderDate] ), \"yyyy-mm-dd\" )"
            ],
            "lineageTag": "615bfc38-e11d-4e79-afa0-ba2c8c750ae2"
          },
          {
            "name": "Days In Business",
            "displayFolder": "Calculations",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Days In Business",
              "",
              "DATEDIFF ( [MinOrderDate], [MaxOrderDate], DAY )"
            ],
            "formatString": "#,0",
            "lineageTag": "0c9f9ab7-0939-4a43-8687-137da40e5b4c"
          },
          {
            "name": "Qty Sales - P01",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P01",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P1\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9125a409-3597-4d98-a38d-61b9d93aa1c7"
          },
          {
            "name": "Qty Sales - P02",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P02",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P2\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "16313bf6-32e9-4692-a40a-a68a2128a45f"
          },
          {
            "name": "Qty Sales - P03",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P03",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P3\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "fd44dd48-28e2-4fe4-8d81-7e28aaf7ca25"
          },
          {
            "name": "Qty Sales - P04",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P04",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P4\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "6831fe5c-0d8e-454e-b43c-cfdb180c5ff5"
          },
          {
            "name": "Qty Sales - P05",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P05",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P5\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "48308c35-c938-4cac-ae01-5391734aa22e"
          },
          {
            "name": "Qty Sales - P06",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P06",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P6\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "20a249c6-7930-4199-8c3b-cda453f4aa77"
          },
          {
            "name": "Qty Sales - P07",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P07",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P7\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "02f5b40d-490f-4fef-884d-d303954a12c2"
          },
          {
            "name": "Qty Sales - P08",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P08",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P8\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "b3a4e5c1-051a-4280-a317-cf9d53ec2789"
          },
          {
            "name": "Qty Sales - P09",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P09",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P9\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "fa53d97c-30fa-48b8-b880-90715d4ad493"
          },
          {
            "name": "Qty Sales - P10",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P10",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P10\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "68c39ab1-987c-4d08-add7-4f4aebfea039"
          },
          {
            "name": "Qty Sales - P11",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P11",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P11\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "f529a5cf-cf48-49ea-91f1-757fee67b9fc"
          },
          {
            "name": "Qty Sales - P12",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P12",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P12\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "0dceeeea-1dfc-47c0-ae70-cdefe9457be2"
          },
          {
            "name": "Qty Sales - P13",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P13",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P13\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "09e26468-2e68-40ab-a36e-4b12a1a12597"
          },
          {
            "name": "Qty Sales - P14",
            "displayFolder": "Qty Sales\\By Period",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - P14",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"P14\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "9f856e5a-a46a-4189-8377-535d3388f9a1"
          },
          {
            "name": "Qty Sales - Current",
            "description": "Qty Sales - Current",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - Current",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"Current\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "d4290736-500b-4d53-b296-b23bafa153b3"
          },
          {
            "name": "Qty Sales - ITD",
            "description": "Qty Sales  - Inception to Date",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - ITD",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"ITD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "74b13617-98c6-4497-abcb-dfa4eba7077d"
          },
          {
            "name": "Qty Sales - MTD",
            "description": "Qty Sales  - Month to Date",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - MTD",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"MTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "14995c60-aaf5-4001-ba40-6d627ce94ef0"
          },
          {
            "name": "Qty Sales - PP",
            "description": "Qty Sales  - Prior Period",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - PP",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PP\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "6028513f-a0cf-4e2e-8e16-f23552ba8a92"
          },
          {
            "name": "Qty Sales - PY",
            "description": "Qty Sales  - Prior Year",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - PY",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "33471b66-9972-4c74-96d3-faf8c05f9d2f"
          },
          {
            "name": "Qty Sales - PY ITD",
            "description": "Qty Sales  - Prior Year Inception to Date",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - PY ITD",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY ITD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "1a8259ba-607e-476b-8ea7-3b5b6f832766"
          },
          {
            "name": "Qty Sales - PY MTD",
            "description": "Qty Sales  - Prior Year Month to Date",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - PY MTD",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY MTD",
              "        \"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "37be48eb-3261-464e-a838-b64c2b9497ab"
          },
          {
            "name": "Qty Sales - PY QTD",
            "description": "Qty Sales  - Prior Year Quarter to Date",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - PY QTD",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "4afba63c-b40c-40f2-96d9-864e42fe6b78"
          },
          {
            "name": "Qty Sales - PY YTD",
            "description": "Qty Sales  - Prior Year Year to Date",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - PY YTD",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"PY YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "13588214-9451-4ecb-9449-1f4b3dfc78e9"
          },
          {
            "name": "Qty Sales - QTD",
            "description": "Qty Sales  - Quarter to Date",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - QTD",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"QTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "5c2965cd-7be9-4836-a11a-1db3df27ceb9"
          },
          {
            "name": "Qty Sales - YTD",
            "description": "Qty Sales  - Year to Date",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - YTD",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"YTD\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "540f83b2-b2e0-4e79-9079-29faa8a6b48b"
          },
          {
            "name": "Qty Sales - YTtotal",
            "description": "Qty Sales  - Year Total",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - YTtotal",
              "",
              "CALCULATE (",
              "    [Qty Sales_input],",
              "    FILTER (",
              "        _TemporalCalculations,",
              "        _TemporalCalculations[Temporal Scope] = \"YTotal\"",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "lineageTag": "e6e04b39-c4f7-45c1-9957-20dcf465be17"
          },
          {
            "name": "Qty Sales_input",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "description": "Qty Sales  - Input Measure",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales_input",
              "",
              "-- I do this so later on we can add a switch for live currency conversion - Tom Sampson 20230901",
              "SUM ( Sales[OrderQuantity] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "lineageTag": "e876da13-a2e8-43a6-9c6b-c3818c2bd5fa"
          },
          {
            "name": "Qty Sales - Current vs PP",
            "description": "Qty Sales - Current - PY",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - Current vs PP",
              "",
              "[Qty Sales - Current] - [Qty Sales - PP]"
            ],
            "formatString": "#,##0",
            "lineageTag": "77a7971d-0c53-4bb1-9c8c-f65dcf700a08"
          },
          {
            "name": "Qty Sales - Current vs PP%",
            "description": "Qty Sales - Current vs PY / PY",
            "displayFolder": "Qty Sales",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Qty Sales - Current vs PP%",
              "",
              "DIVIDE (",
              "    [Qty Sales - Current vs PP],",
              "    [Qty Sales - PP],",
              "    BLANK ( )",
              ")"
            ],
            "formatString": "#,##0 %",
            "lineageTag": "9914fc16-d70d-42d0-910d-1352d4a15da8"
          },
          {
            "name": "Amt Sales Ext vs PP",
            "description": "Amt Sales Ext  - Current - Prior Year",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext vs PY",
              "",
              "[Amt Sales Ext - Current] - [Amt Sales Ext - PP]"
            ],
            "formatString": "#,##0",
            "lineageTag": "f98e4bcc-9b7e-491c-bc8e-1994043166e3"
          },
          {
            "name": "Amt Sales Ext vs PP %",
            "description": "[Amt Sales Ext vs PY] / [Amt Sales Ext PY] ",
            "displayFolder": "Amt Sales Ext",
            "expression": [
              "// Tom Sampson © Clutch.Net 2023 MIT License",
              "// 2023-09-17 00:15:34 - Amt Sales Ext vs PY %",
              "",
              "IF(",
              "    [Amt Sales Ext vs PP] <> 0 && [Amt Sales Ext - PP] = 0,",
              "    1,",
              "    DIVIDE( [Amt Sales Ext vs PP], [Amt Sales Ext - PP] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7927bb12-c8e7-4c5b-8611-5c899826d43e"
          }
        ],
        "partitions": [
          {
            "name": "Sales",
            "mode": "import",
            "source": {
              "expression": [
                "// Sales + 20 years for Clutch.Net Tutorial & Demo - Tom Sampson © Clutch.Net 2023",
                "// free to use under the MIT License. See project LICENSE for more details.",
                "let",
                "    // Load the Sales data from the Excel file",
                "    DataSourceParam = #\"DataSource\",",
                "    Source = Excel.Workbook(File.Contents(DataSourceParam), null, true),",
                "    SalesData = Source{[Item=\"Sales\",Kind=\"Sheet\"]}[Data],",
                "",
                "    // Promote headers",
                "    PromotedHeaders = Table.PromoteHeaders(SalesData, [PromoteAllScalars=true]),",
                "",
                "    // Split SalesOrderNumber column based on position",
                "    SplitOrderNumber = Table.SplitColumn(PromotedHeaders, \"SalesOrderNumber\", Splitter.SplitTextByPositions({0, 2}, false), {\"OrderPrefix\", \"OrderKey\"}),",
                "    RemovedOrderPrefix = Table.RemoveColumns(SplitOrderNumber, {\"OrderPrefix\"}),",
                "",
                "    // Add CustomerOrderKey column by concatenating CustomerKey and OrderKey",
                "    AddedCustomerOrderKey = Table.AddColumn(RemovedOrderPrefix, \"CustomerOrderKey\", each Text.From([CustomerKey]) & Text.From([OrderKey])),",
                "",
                "    // Set column types for specified columns",
                "    TypedColumns = Table.TransformColumnTypes(AddedCustomerOrderKey, {",
                "        {\"OrderKey\", Int64.Type},",
                "        {\"ProductKey\", Int64.Type},",
                "        {\"SalesTerritoryKey\", Int64.Type},",
                "        {\"SalesOrderLineNumber\", Int64.Type},",
                "        {\"OrderQuantity\", Int64.Type},",
                "        {\"DiscountAmount\", Int64.Type},",
                "        {\"OrderDate\", type date},",
                "        {\"CustomerKey\", Int64.Type},",
                "        {\"ProductStandardCost\", type number},",
                "        {\"SalesAmount\", type number}",
                "    }),",
                "",
                "    // Add 20 years to OrderDate",
                "    ExtendedDate = Table.TransformColumns(TypedColumns, {\"OrderDate\", each Date.AddYears(_, 20)}),",
                "",
                "    // Filter rows where OrderDate <= today's date",
                "    FilteredRows = Table.SelectRows(ExtendedDate, each [OrderDate] <= DateTime.Date(DateTime.LocalNow())),",
                "",
                "    // Add DateKey column based on the OrderDate",
                "    DateKey = Table.AddColumn(FilteredRows, \"DateKey\", each Text.From(Date.Year([OrderDate])) & Text.End(Text.PadStart(Text.From(Date.Month([OrderDate]), \"en-US\"), 2, \"0\"), 2) & Text.End(Text.PadStart(Text.From(Date.Day([OrderDate]), \"en-US\"), 2, \"0\"), 2)),",
                "    TypedDateKey = Table.TransformColumnTypes(DateKey, {{\"DateKey\", Int64.Type}}),",
                "",
                "    // Add CustomerDateKey column by concatenating CustomerKey and OrderDateKey",
                "    CustomerDateKey = Table.AddColumn(TypedDateKey, \"CustomerDateKey\", each Text.From([CustomerKey]) & Text.From([DateKey])),",
                "    ",
                "    // Ensure CustomerOrderKey is a text column for concatenation",
                "    TextCustomerOrderKey = Table.TransformColumnTypes(CustomerDateKey, {{\"CustomerOrderKey\", type text}, {\"CustomerDateKey\", type text}}),",
                "",
                "    // Concatenate \"1\" to the end of CustomerOrderKey and CustomerDateKey",
                "    ConcatenateKeys = Table.TransformColumns(TextCustomerOrderKey, {",
                "        {\"CustomerOrderKey\", each _ & \"1\", type text},",
                "        {\"CustomerDateKey\", each _ & \"1\", type text}",
                "    }),",
                "",
                "    // Convert the concatenated columns back to whole numbers",
                "    NumericKeys = Table.TransformColumnTypes(ConcatenateKeys, {",
                "        {\"CustomerOrderKey\", Int64.Type},",
                "        {\"CustomerDateKey\", Int64.Type}",
                "    }),",
                "",
                "    // Rename columns for better readability",
                "    RenamedColumns = Table.RenameColumns(NumericKeys,{{\"Territories.Region\", \"Region\"}, {\"Territories.Country\", \"Country\"}, {\"Territories.Continent\", \"Continent\"}})",
                "in",
                "    RenamedColumns"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a018a214-8799-41a6-a8f6-1f39ede573d4",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "49a7e701-e959-4c52-b7a4-b12643c46268",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "BirthDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2f988b67-7758-41d2-a221-404a3d59e482",
            "sourceColumn": "BirthDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_658f918d-6afb-47b1-a543-93834dba1dd4"
                },
                "isDefault": true,
                "relationship": "c7c8aea1-f13f-459c-ab2b-3d8cc99c02fa"
              }
            ]
          },
          {
            "name": "MaritalStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c929fa8-54b1-4c5d-a466-ef17918c2ca7",
            "sourceColumn": "MaritalStatus",
            "summarizeBy": "none"
          },
          {
            "name": "Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b669d4ee-c5fd-4537-ade6-0b9c4f1d4e1c",
            "sourceColumn": "Gender",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0de2c5d7-5069-4e5d-b04b-6348f9aff3ac",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "YearlyIncome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b922de8-34fb-4567-bc1c-2e442c936e2e",
            "sourceColumn": "YearlyIncome",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalChildren",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cb20b794-10f3-4993-9f85-3f9c6243adc4",
            "sourceColumn": "TotalChildren",
            "summarizeBy": "sum"
          },
          {
            "name": "Education",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b594f2b-b9a3-4727-a023-489d363ba903",
            "sourceColumn": "Education",
            "summarizeBy": "none"
          },
          {
            "name": "Occupation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23d3d99f-bc43-4b07-b692-d0ca2fe9536d",
            "sourceColumn": "Occupation",
            "summarizeBy": "none"
          },
          {
            "name": "HouseOwnerFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "718b00c2-2ff8-46eb-ac88-11b32eeba249",
            "sourceColumn": "HouseOwnerFlag",
            "summarizeBy": "sum"
          },
          {
            "name": "NumberCarsOwned",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5e541c8d-46b9-497c-857b-215f2a2e41ee",
            "sourceColumn": "NumberCarsOwned",
            "summarizeBy": "sum"
          },
          {
            "name": "AddressLine1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c2ef527-ca21-4553-afa8-85123826fe07",
            "sourceColumn": "AddressLine1",
            "summarizeBy": "none"
          },
          {
            "name": "DateFirstPurchase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "eb9f41b4-c04e-4ffb-8aea-1a102e20ab67",
            "sourceColumn": "DateFirstPurchase",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b6a9521f-0ebc-4753-8251-bfe1e184c038"
                },
                "isDefault": true,
                "relationship": "b872ddfd-3b03-41fb-bc35-a032052be36c"
              }
            ]
          },
          {
            "name": "CommuteDistance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba34551c-fd5a-4f2d-beb0-172116eb68af",
            "sourceColumn": "CommuteDistance",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ac4f67e2-048c-4563-b816-1551a18a64b7",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "adddb860-4acd-4a4b-af28-1bdc8e2ca865",
        "partitions": [
          {
            "name": "Customer",
            "mode": "import",
            "source": {
              "expression": [
                "// Customer + 20 years for Clutch.Net Tutorial & Demo - Tom Sampson © Clutch.Net 2023",
                "// free to use under the MIT License. See project LICENSE for more details.",
                "let",
                "    DataSourceParam = #\"DataSource\",",
                "    Source = Excel.Workbook(File.Contents(DataSourceParam), null, true),",
                "    Customers_Sheet = Source{[Item=\"Customers\",Kind=\"Sheet\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Customers_Sheet, [PromoteAllScalars=true]),",
                "    #\"Adjusted BirthDate\" = Table.TransformColumns(#\"Promoted Headers\", {\"BirthDate\", each Date.AddYears(_, 20)}),",
                "    #\"Adjusted DateFirstPurchase\" = Table.TransformColumns(#\"Adjusted BirthDate\", {\"DateFirstPurchase\", each Date.AddYears(_, 20)}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Adjusted DateFirstPurchase\", {",
                "        {\"CustomerKey\", Int64.Type}, {\"AltCustomerKey\", Int64.Type}, {\"FirstName\", type text}, ",
                "        {\"LastName\", type text}, {\"BirthDate\", type date}, {\"MaritalStatus\", type text}, ",
                "        {\"Gender\", type text}, {\"EmailAddress\", type text}, {\"YearlyIncome\", Int64.Type}, ",
                "        {\"TotalChildren\", Int64.Type}, {\"EnglishEducation\", type text}, {\"EnglishOccupation\", type text}, ",
                "        {\"HouseOwnerFlag\", Int64.Type}, {\"NumberCarsOwned\", Int64.Type}, {\"AddressLine1\", type text}, ",
                "        {\"DateFirstPurchase\", type date}, {\"CommuteDistance\", type text}",
                "    }),",
                "    #\"Trimmed Text\" = Table.TransformColumns(#\"Changed Type\", {",
                "        {\"MaritalStatus\", Text.Trim, type text}, {\"Gender\", Text.Trim, type text}, ",
                "        {\"EmailAddress\", Text.Trim, type text}, {\"EnglishEducation\", Text.Trim, type text}, ",
                "        {\"EnglishOccupation\", Text.Trim, type text}, {\"AddressLine1\", Text.Trim, type text}, ",
                "        {\"CommuteDistance\", Text.Trim, type text}",
                "    }),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Trimmed Text\", {",
                "        {\"EnglishEducation\", \"Education\"}, {\"EnglishOccupation\", \"Occupation\"}, {\"CustomerKey\", \"CustomerKey_orig\"}",
                "    }),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"CustomerKey\", each ",
                "        if [CustomerKey_orig] < [AltCustomerKey] then [CustomerKey_orig] else [AltCustomerKey]",
                "    ),",
                "    #\"Changed Type Final\" = Table.TransformColumnTypes(#\"Added Custom\", {{\"CustomerKey\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type Final\",{\"AltCustomerKey\", \"CustomerKey_orig\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_658f918d-6afb-47b1-a543-93834dba1dd4",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c369f499-7bcb-41f3-8849-bb75692602d3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5cd13816-490a-414c-9e2c-2498acb62eaa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e63eebde-139f-49d3-b3e3-bf3058a11465",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ad4dc189-d2e6-4d4f-b47f-df137e54b5f4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8f6ce4b3-f7d0-4b75-a1e9-99ffae9a0418",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4900d994-8498-46f8-82f1-f5601104bab3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4e000eb9-104a-4cf1-9ecd-a69ea77eff72",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "bbe6c81d-c363-4eb2-b1df-86c083498f37",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "36728b94-f0cf-4dbb-9b47-6d1bfd6fe990",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8352151b-01d7-4d63-9e1b-6c9b344c10b5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1f27c287-2a6e-4e16-90ff-38fc143f460d",
                "ordinal": 3
              }
            ],
            "lineageTag": "e4d363a5-3f7c-4778-b036-55681e232698"
          }
        ],
        "isHidden": true,
        "lineageTag": "08ead50b-4822-4f42-98d9-7295eedc7b48",
        "partitions": [
          {
            "name": "LocalDateTable_658f918d-6afb-47b1-a543-93834dba1dd4",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Customer'[BirthDate])), 1, 1), Date(Year(MAX('Customer'[BirthDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b6a9521f-0ebc-4753-8251-bfe1e184c038",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5d4c85c7-57b1-430a-80ef-3c1671c3e463",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a0a51df2-e111-4a43-8d7a-f2f5d6d2d5e5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "38f2996e-57a7-4bf9-95f5-175cf971eaac",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "930cab45-5bce-4ab1-b0b1-a8efc0f8214c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fe14dca8-d886-4039-81e1-1882ddcebebb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "da420689-1463-41b9-828b-c042fc9453f7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e24f7985-6ae4-4baf-9abd-db3607679e9c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "af08d9d9-4262-4982-af06-823aeac737f1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6bf02eaf-4933-45f7-8b72-5b2ff7e615ff",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9c1524cb-c795-44d1-ae76-567c6cacba5b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "30bc7710-0f4d-4e73-bca5-bee7a5683249",
                "ordinal": 3
              }
            ],
            "lineageTag": "965d1366-fe96-4c84-bfef-54d0017f0967"
          }
        ],
        "isHidden": true,
        "lineageTag": "8a25c992-0c33-440f-af73-1ecc3dc99beb",
        "partitions": [
          {
            "name": "LocalDateTable_b6a9521f-0ebc-4753-8251-bfe1e184c038",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Customer'[DateFirstPurchase])), 1, 1), Date(Year(MAX('Customer'[DateFirstPurchase])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Products",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e32d87ec-f12f-42c2-ab08-8e9a930ce03e",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "Subcategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfd5181c-8f4b-4efa-9c6c-6b8c0e19cf56",
            "sourceColumn": "Subcategory",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "612d6792-a82a-4c24-8fd3-4fb654f5aa2f",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "StandardCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "09523e91-e3de-4ea3-87ac-de5719a69831",
            "sourceColumn": "StandardCost",
            "summarizeBy": "sum"
          },
          {
            "name": "FinishedGoodsFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "aff2ae8a-4cca-4dc5-b3fc-13f55b19ec32",
            "sourceColumn": "FinishedGoodsFlag",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b3681b5-ebb6-4610-9b8f-3b4a50987c05",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "ListPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c1a63a9f-4dd8-41d4-b44d-eb87b35c42ca",
            "sourceColumn": "ListPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "Size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a90f14f7-5f0f-4ab3-bd87-e798c88e9fef",
            "sourceColumn": "Size",
            "summarizeBy": "none"
          },
          {
            "name": "ProductLine",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b82c81b-9103-4839-b68d-84233c6029d8",
            "sourceColumn": "ProductLine",
            "summarizeBy": "none"
          },
          {
            "name": "DealerPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b401b11b-3eed-4216-a408-358e61692b0a",
            "sourceColumn": "DealerPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "Class",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1b006f4-9539-4cf4-9bdd-ad8f838d61f8",
            "sourceColumn": "Class",
            "summarizeBy": "none"
          },
          {
            "name": "Style",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a4c3a8c7-2357-4f66-9b29-57555eb12720",
            "sourceColumn": "Style",
            "summarizeBy": "none"
          },
          {
            "name": "ModelName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06d266cf-6885-4eba-b4dd-ec95170d3013",
            "sourceColumn": "ModelName",
            "summarizeBy": "none"
          },
          {
            "name": "StartDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "4390607d-d54a-419f-9feb-45cb291388e8",
            "sourceColumn": "StartDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_5dc773a6-a3b2-4bdb-9b3f-5484aa38e464"
                },
                "isDefault": true,
                "relationship": "9ffc2b5b-43c1-4aca-bfb5-8471fb6df363"
              }
            ]
          },
          {
            "name": "EndDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm-dd",
            "lineageTag": "1d5339b2-c35c-4a01-8de7-d67141318891",
            "sourceColumn": "EndDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_61c7a7cc-d989-45fc-85ae-3996feaf02e1"
                },
                "isDefault": true,
                "relationship": "52cb8cbf-667f-4e08-9ad5-51394a9d6186"
              }
            ]
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44f0e2ae-7c39-401b-aebe-23bd246e6e72",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "Product ID & Desc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "FORMAT( Products[ProductKey], \"0\" ) & \" - \"",
              "    & Products[ProductName]"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "263edc8f-933a-458c-a548-9ef4f9640ff6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "d65245b7-3a4a-4f74-83aa-9303e7f5c1a8",
        "partitions": [
          {
            "name": "Products",
            "mode": "import",
            "source": {
              "expression": [
                "// Products + 20 years for Clutch.Net Tutorial & Demo - Tom Sampson © Clutch.Net 2023",
                "// free to use under the MIT License. See project LICENSE for more details.",
                "",
                "let",
                "    // Load data from the Excel file",
                "    DataSourceParam = #\"DataSource\",",
                "    Source = Excel.Workbook(File.Contents(DataSourceParam), null, true),",
                "    ",
                "    // Select the 'Products' sheet",
                "    Products_Sheet = Source{[Item=\"Products\",Kind=\"Sheet\"]}[Data],",
                "    ",
                "    // Promote the first row as headers",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Products_Sheet, [PromoteAllScalars=true]),",
                "    ",
                "    // Change column types",
                "    #\"Changed Type\" = Table.TransformColumnTypes(",
                "        #\"Promoted Headers\",",
                "        {",
                "            {\"ProductKey\", Int64.Type}, {\"EnglishProductName\", type text}, {\"StandardCost\", type number}, ",
                "            {\"FinishedGoodsFlag\", type logical}, {\"Color\", type text}, {\"ListPrice\", type number}, ",
                "            {\"Size\", type text}, {\"ProductLine\", type text}, {\"DealerPrice\", type number}, ",
                "            {\"Class\", type text}, {\"Style\", type text}, {\"ModelName\", type text}, ",
                "            {\"StartDate\", type datetime}, {\"EndDate\", type datetime}, {\"Status\", type text}, ",
                "            {\"Subcategory\", type text}",
                "        }",
                "    ),",
                "    ",
                "    // Reorder columns for better readability",
                "    #\"Reordered Columns\" = Table.ReorderColumns(",
                "        #\"Changed Type\",",
                "        {\"ProductKey\", \"Subcategory\", \"EnglishProductName\", \"StandardCost\", \"FinishedGoodsFlag\", ",
                "         \"Color\", \"ListPrice\", \"Size\", \"ProductLine\", \"DealerPrice\", \"Class\", \"Style\", ",
                "         \"ModelName\", \"StartDate\", \"EndDate\", \"Status\"}",
                "    ),",
                "    ",
                "    // Trim text columns to remove unwanted spaces",
                "    #\"Trimmed Text\" = Table.TransformColumns(",
                "        #\"Reordered Columns\",",
                "        {",
                "            {\"Size\", Text.Trim, type text}, {\"ProductLine\", Text.Trim, type text}, ",
                "            {\"Class\", Text.Trim, type text}, {\"Style\", Text.Trim, type text}, ",
                "            {\"ModelName\", Text.Trim, type text}",
                "        }",
                "    ),",
                "    ",
                "    // Convert 'StartDate' from datetime to date type",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Trimmed Text\",{{\"StartDate\", type date}}),",
                "    ",
                "    // Extract only the date from 'EndDate'",
                "    #\"Extracted Date\" = Table.TransformColumns(#\"Changed Type1\",{{\"EndDate\", DateTime.Date, type date}}),",
                "    ",
                "    // Trim 'Status' column",
                "    #\"Trimmed Text1\" = Table.TransformColumns(#\"Extracted Date\",{{\"Status\", Text.Trim, type text}}),",
                "    ",
                "    // Rename the 'EnglishProductName' column",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Trimmed Text1\",{{\"EnglishProductName\", \"ProductName\"}}),",
                "    ",
                "    // Rename original date columns for later adjustments",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Renamed Columns\",{{\"StartDate\", \"StartDate_orig\"}, {\"EndDate\", \"EndDate_orig\"}}),",
                "    ",
                "    // Add 20 years to the original 'StartDate'",
                "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns1\", \"StartDate\", each Date.AddYears([StartDate_orig], 20)),",
                "    ",
                "    // Add 20 years to the original 'EndDate'",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Added Custom\", \"EndDate\", each Date.AddYears([EndDate_orig], 20)),",
                "    ",
                "    // Remove original date columns",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Added Custom1\",{\"StartDate_orig\", \"EndDate_orig\"}),",
                "    ",
                "    // Filter out products with future 'StartDate'",
                "    #\"Filtered Future Dates\" = Table.SelectRows(#\"Removed Columns\", each [StartDate] <= Date.From(DateTime.LocalNow())),",
                "    ",
                "    // Adjust 'StartDate' and 'EndDate' types",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Filtered Future Dates\",{{\"StartDate\", type date}, {\"EndDate\", type date}}),",
                "    ",
                "    // Rename 'Status' column for status calculation",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type2\",{{\"Status\", \"Status_orig\"}}),",
                "    ",
                "    // Calculate 'Status' based on 'StartDate' and 'EndDate'",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Renamed Columns2\", \"Status\", each ",
                "        if [StartDate] <= Date.From(DateTime.LocalNow()) and ([EndDate] = null or [EndDate] > Date.From(DateTime.LocalNow())) ",
                "        then \"Current\" ",
                "        else null",
                "    ),",
                "    ",
                "    // Convert 'Status' column to text",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"Status\", type text}}),",
                "    ",
                "    // Remove the original 'Status' column",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type3\",{\"Status_orig\"})",
                "in",
                "    #\"Removed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_5dc773a6-a3b2-4bdb-9b3f-5484aa38e464",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2ac7170b-a694-4225-a6cd-265380e66ef4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ff4232c0-fe39-4c2c-abed-06b92dd5c5a4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0abe0c4a-abeb-4dba-a861-b2d79c3695ae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c63cd06d-23a8-4518-82ec-db39a69cff92",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2b45b28d-414a-4f4a-8d26-b89e604dd8ce",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3e97a784-b77b-4537-b4f0-2ebbaa0223f2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fb98b6df-5b1f-465b-b354-1f6e2400ff98",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f5cacd7c-177a-45d8-b6c1-2a4ef283b591",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a90f3e85-792d-4f18-ae2a-4c8164ada28f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4ae98edb-4bb5-4782-a36e-e722b7384726",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a085ba87-cee0-4a32-9b99-f14f00e5ab3d",
                "ordinal": 3
              }
            ],
            "lineageTag": "96536f8e-b2e3-4702-8054-5e0b97c24675"
          }
        ],
        "isHidden": true,
        "lineageTag": "5594e1b1-d470-4cf5-9eda-f7aa8caea9cc",
        "partitions": [
          {
            "name": "LocalDateTable_5dc773a6-a3b2-4bdb-9b3f-5484aa38e464",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Products'[StartDate])), 1, 1), Date(Year(MAX('Products'[StartDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_61c7a7cc-d989-45fc-85ae-3996feaf02e1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "67aec76c-1992-405e-b107-ce7ed9232fc3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c548efbf-8d01-4bc1-ac0c-48d93d3d3287",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0178ec54-b0fc-43fb-8f08-e532bbdb02a3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "58e42785-e54c-4bc4-92c0-dce684bbd053",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c449e959-78e6-43d8-af4e-a13aa8085f14",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b1510c91-3236-4b3e-ba9a-62eddffdfe4e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "01b518ac-0aa8-4b41-bd77-546d741e513f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "6a951c7e-05fd-4586-91b6-01540dcf431e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8948d1dc-19ec-4a67-aec0-44a65b4dde90",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0a4948a1-980d-408e-9ac3-697a4487052a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "bc729c83-b61a-4b76-ba68-076f62f82d44",
                "ordinal": 3
              }
            ],
            "lineageTag": "9c4ac531-2652-4371-9ea5-0d0c0bd86ca8"
          }
        ],
        "isHidden": true,
        "lineageTag": "7e438b2d-1cbe-4896-ad4f-9ab7c1efb285",
        "partitions": [
          {
            "name": "LocalDateTable_61c7a7cc-d989-45fc-85ae-3996feaf02e1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Products'[EndDate])), 1, 1), Date(Year(MAX('Products'[EndDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "CountryCodes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d745332d-aca0-40ed-ab9c-bc2c5ab6a5c4",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8a13312-9d49-4391-b79d-fa8ef8aa589d",
            "sourceColumn": "Code",
            "summarizeBy": "none"
          },
          {
            "name": "FlagIconURL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageURL",
            "dataType": "string",
            "lineageTag": "58c7fa72-0d75-46bb-b4dc-7960225e4952",
            "sourceColumn": "FlagIconURL",
            "summarizeBy": "none"
          },
          {
            "name": "FlagSmallURL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageURL",
            "dataType": "string",
            "lineageTag": "2f47ae6f-4d94-41b5-8a63-b2a063ab29ff",
            "sourceColumn": "FlagSmallURL",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3d177bbc-ab8d-4e82-a1ce-d16e2442c4b6",
        "partitions": [
          {
            "name": "CountryCodes",
            "mode": "import",
            "source": {
              "expression": [
                "// CountryCodes for Clutch.Net Tutorial & Demo - Tom Sampson © Clutch.Net 2023",
                "// free to use under the MIT License. See project LICENSE for more details.",
                "",
                "let",
                "    Source = #table({\"Country\", \"Code\"}, ",
                "    {",
                "        {\"Australia\", \"AU\"},",
                "        {\"Canada\", \"CA\"},",
                "        {\"France\", \"FR\"},",
                "        {\"Germany\", \"DE\"},",
                "        {\"United Kingdom\", \"GB\"},",
                "        {\"United States\", \"US\"}",
                "    }),",
                "    #\"Added FlagIconURL\" = Table.AddColumn(Source, \"FlagIconURL\", each \"https://clutch.net/flags/icons/\" & [Code] & \".png\"),",
                "    #\"Added FlagSmallURL\" = Table.AddColumn(#\"Added FlagIconURL\", \"FlagSmallURL\", each \"https://clutch.net/flags/small/\" & [Code] & \".png\")",
                "in",
                "    #\"Added FlagSmallURL\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ProductCategories",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Subcategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9931b78-000a-45fe-bf65-0011163825fc",
            "sourceColumn": "Subcategory",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "230d744a-be4e-41ce-ae4b-caea798bc7af",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fae3f75c-5251-40cc-8f4b-5887679c3b4e",
        "partitions": [
          {
            "name": "ProductCategories",
            "mode": "import",
            "source": {
              "expression": [
                "// ProductCategories for Clutch.Net Tutorial & Demo - Tom Sampson © Clutch.Net 2023",
                "// Free to use under the MIT License. See project LICENSE for more details.",
                "",
                "let",
                "    // Load data from the Excel file",
                "    DataSourceParam = #\"DataSource\",",
                "    Source = Excel.Workbook(File.Contents(DataSourceParam), null, true),",
                "    ",
                "    // Select the 'ProductCategories' sheet",
                "    ProductCategories_Sheet = Source{[Item=\"ProductCategories\",Kind=\"Sheet\"]}[Data],",
                "    ",
                "    // Initially set data types for the loaded columns",
                "    ChangedType = Table.TransformColumnTypes(",
                "        ProductCategories_Sheet,",
                "        {",
                "            {\"Column1\", type text},",
                "            {\"Column2\", type text}",
                "        }",
                "    ),",
                "    ",
                "    // Promote the first row as headers",
                "    PromotedHeaders = Table.PromoteHeaders(ChangedType, [PromoteAllScalars=true]),",
                "    ",
                "    // Correctly set the data types of the newly promoted headers",
                "    ChangedType1 = Table.TransformColumnTypes(",
                "        PromotedHeaders,",
                "        {",
                "            {\"Subcategory\", type text},",
                "            {\"Category\", type text}",
                "        }",
                "    )",
                "    ",
                "in",
                "    ChangedType1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CustomerProductBridge",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "18086074-d870-43dc-a6be-1b0889fab26d",
            "sourceColumn": "CustomerKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2ea31347-58ee-4c9d-91b2-2ad5494b1aef",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "eb1a9523-702d-4655-be00-5553e74669e9",
        "partitions": [
          {
            "name": "CustomerProductBridge",
            "mode": "import",
            "source": {
              "expression": [
                "// CustomerProductBridge for Clutch.Net Tutorial & Demo - Tom Sampson © Clutch.Net 2023",
                "// free to use under the MIT License. See project LICENSE for more details.",
                "",
                "let",
                "    // Load data from the Excel file",
                "    DataSourceParam = #\"DataSource\",",
                "    Source = Excel.Workbook(File.Contents(DataSourceParam), null, true),",
                "    ",
                "    // Select the 'Sales' sheet",
                "    Sales_Sheet = Source{[Item=\"Sales\",Kind=\"Sheet\"]}[Data],",
                "    ",
                "    // Promote the first row as headers",
                "    PromotedHeaders = Table.PromoteHeaders(Sales_Sheet, [PromoteAllScalars=true]),",
                "    ",
                "    // Only select the columns we need",
                "    SelectedColumns = Table.SelectColumns(PromotedHeaders,{\"CustomerKey\", \"ProductKey\"}),",
                "    ",
                "    // Transform types of the columns to integer",
                "    ChangedTypes = Table.TransformColumnTypes(SelectedColumns, {{\"CustomerKey\", Int64.Type}, {\"ProductKey\", Int64.Type}}),",
                "    ",
                "    // Remove duplicate rows to get distinct combinations of CustomerKey and ProductKey",
                "    RemovedDuplicates = Table.Distinct(ChangedTypes)",
                "    ",
                "in",
                "    RemovedDuplicates"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_TemporalCalculations",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Current",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "SELECTEDMEASURE( )"
              ],
              "ordinal": 0
            },
            {
              "name": "MTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Period]",
                "            = MAX( Calendar[Period] )",
                "            && Calendar[CalendarDate] <= MAX( Calendar[CalendarDate] )",
                "    )",
                ")"
              ],
              "ordinal": 1
            },
            {
              "name": "Prior MTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Period]",
                "            = MAX( Calendar[Period] ) - 1",
                "            && Calendar[CalendarDate] <= MAX( Calendar[PPDate] )",
                "    )",
                ")"
              ],
              "ordinal": 2
            },
            {
              "name": "QTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Quarter]",
                "            = MAX( Calendar[Quarter] )",
                "            && Calendar[CalendarDate] <= MAX( Calendar[CalendarDate] )",
                "    )",
                ")"
              ],
              "ordinal": 3
            },
            {
              "name": "Prior QTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Quarter]",
                "            = MAX( Calendar[Quarter] ) - 1",
                "            && Calendar[CalendarDate] <= MAX( Calendar[PQDate] )",
                "    )",
                ")"
              ],
              "ordinal": 4
            },
            {
              "name": "YTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[CalendarDate] <= MAX( Calendar[CalendarDate] )",
                "    )",
                ")"
              ],
              "ordinal": 5
            },
            {
              "name": "Prior YTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[CalendarDate] <= MAX( Calendar[CalendarDate] )",
                "    )",
                ")"
              ],
              "ordinal": 6
            },
            {
              "name": "ITD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[CalendarDate] <= MAX( Calendar[CalendarDate] )",
                "    )",
                ")"
              ],
              "ordinal": 7
            },
            {
              "name": "Prior Per ITD",
              "description": "Prior Period Inception To Date",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[PriorPeriodYear] )",
                "            && Calendar[CalendarDate] <= MAX( Calendar[PPDate] )",
                "    )",
                ")"
              ],
              "ordinal": 8
            },
            {
              "name": "YTotal",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "    )",
                ")"
              ],
              "ordinal": 9
            },
            {
              "name": "PY YTotal",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] ) - 1",
                "    )",
                ")"
              ],
              "ordinal": 10
            },
            {
              "name": "PY",
              "description": "Prior Year",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[CalendarDate] >= MIN( Calendar[PYDate] )",
                "            && Calendar[CalendarDate] <= MAX( Calendar[PYDate] )",
                "    )",
                ")"
              ],
              "ordinal": 11
            },
            {
              "name": "PY MTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Period]",
                "            = MAX( Calendar[Period] ) - 12",
                "            && Calendar[CalendarDate] <= MAX( Calendar[PYDate] )",
                "    )",
                ")"
              ],
              "ordinal": 12
            },
            {
              "name": "PY QTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Quarter]",
                "            = MAX( Calendar[Quarter] ) - 4",
                "            && Calendar[CalendarDate] <= MAX( Calendar[PYDate] )",
                "    )",
                ")"
              ],
              "ordinal": 13
            },
            {
              "name": "PY YTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] ) - 1",
                "            && Calendar[CalendarDate] <= MAX( Calendar[PYDate] )",
                "    )",
                ")"
              ],
              "ordinal": 14
            },
            {
              "name": "PY ITD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] ) - 1",
                "            && Calendar[CalendarDate] <= MAX( Calendar[PYDate] )",
                "    )",
                ")"
              ],
              "ordinal": 15
            },
            {
              "name": "YoY",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "VAR PY =",
                "    CALCULATE(",
                "        SELECTEDMEASURE( ),",
                "        FILTER(",
                "            ALL( Calendar ),",
                "            Calendar[CalendarDate] >= MIN( Calendar[PYDate] )",
                "                && Calendar[CalendarDate] <= MAX( Calendar[PYDate] )",
                "        )",
                "    )",
                "VAR CY = SELECTEDMEASURE( )",
                "VAR Result = IF( NOT ISBLANK( CY ) && NOT ISBLANK( PY ), CY - PY )",
                "RETURN",
                "    Result"
              ],
              "ordinal": 16
            },
            {
              "name": "Rolling 12",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Period]",
                "            >= MAX( Calendar[Period] ) - 11",
                "            && Calendar[Period]",
                "            <= MAX( Calendar[Period] )",
                "            && Calendar[CalendarDate] <= MAX( Calendar[CalendarDate] )",
                "    )",
                ")"
              ],
              "ordinal": 17
            },
            {
              "name": "P01",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 1",
                "    )",
                ")"
              ],
              "ordinal": 18
            },
            {
              "name": "P02",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 2",
                "    )",
                ")"
              ],
              "ordinal": 19
            },
            {
              "name": "P03",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 3",
                "    )",
                ")"
              ],
              "ordinal": 20
            },
            {
              "name": "P04",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 4",
                "    )",
                ")"
              ],
              "ordinal": 21
            },
            {
              "name": "P05",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 5",
                "    )",
                ")"
              ],
              "ordinal": 22
            },
            {
              "name": "P06",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 6",
                "    )",
                ")"
              ],
              "ordinal": 23
            },
            {
              "name": "P07",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 7",
                "    )",
                ")"
              ],
              "ordinal": 24
            },
            {
              "name": "P08",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 8",
                "    )",
                ")"
              ],
              "ordinal": 25
            },
            {
              "name": "P09",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 9",
                "    )",
                ")"
              ],
              "ordinal": 26
            },
            {
              "name": "P10",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 10",
                "    )",
                ")"
              ],
              "ordinal": 27
            },
            {
              "name": "P11",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 11",
                "    )",
                ")"
              ],
              "ordinal": 28
            },
            {
              "name": "P12",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 12",
                "    )",
                ")"
              ],
              "ordinal": 29
            },
            {
              "name": "P13",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 13",
                "    )",
                ")"
              ],
              "ordinal": 30
            },
            {
              "name": "P14",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year]",
                "            = MAX( Calendar[Year] )",
                "            && Calendar[Period] = 14",
                "    )",
                ")"
              ],
              "ordinal": 31
            },
            {
              "name": "PP",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year] = ",
                "            IF(",
                "                MAX(Calendar[Period]) = 1,",
                "                MAX(Calendar[Year]) - 1,",
                "                MAX(Calendar[Year])",
                "            )",
                "            && Calendar[Period] = ",
                "            IF(",
                "                MAX(Calendar[Period]) = 1,",
                "                12,",
                "                MAX(Calendar[Period]) - 1",
                "            )",
                "    )",
                ")"
              ],
              "ordinal": 32
            }
          ],
          "precedence": 55
        },
        "columns": [
          {
            "name": "Temporal Scope",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ae5959f-3140-4130-a5fc-db04e3b00928",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "d56d32f2-ffdc-4d03-b1db-8026f8e23092",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "2059cfa8-8cf2-481a-9723-d72a31f76f8e",
        "partitions": [
          {
            "name": "TemporalCalculationGroup",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "_TemporalFiscalCalculations",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Current",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "SELECTEDMEASURE( )"
              ],
              "ordinal": 0
            },
            {
              "name": "YoY",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "VAR PY =",
                "    CALCULATE(",
                "        SELECTEDMEASURE( ),",
                "        FILTER(",
                "            ALL( Calendar ),",
                "            Calendar[FiscalDate] >= MIN( Calendar[FiscalPYDate] )",
                "                && Calendar[FiscalDate] <= MAX( Calendar[FiscalPYDate] )",
                "        )",
                "    )",
                "VAR CY = SELECTEDMEASURE( )",
                "VAR Result = IF( NOT ISBLANK( CY ) && NOT ISBLANK( PY ), CY - PY )",
                "RETURN",
                "    Result"
              ],
              "ordinal": 1
            },
            {
              "name": "MTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalPeriod]",
                "            = MAX( Calendar[FiscalPeriod] )",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalDate] )",
                "    )",
                ")"
              ],
              "ordinal": 2
            },
            {
              "name": "Prior MTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalPeriod]",
                "            = MAX( Calendar[FiscalPeriod] ) - 1",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalPPDate] )",
                "    )",
                ")"
              ],
              "ordinal": 3
            },
            {
              "name": "QTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalQuarter]",
                "            = MAX( Calendar[FiscalQuarter] )",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalDate] )",
                "    )",
                ")"
              ],
              "ordinal": 4
            },
            {
              "name": "Prior QTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalQuarter]",
                "            = MAX( Calendar[FiscalQuarter] ) - 1",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalPQDate] )",
                "    )",
                ")"
              ],
              "ordinal": 5
            },
            {
              "name": "YTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalDate] )",
                "    )",
                ")"
              ],
              "ordinal": 6
            },
            {
              "name": "Prior YTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalDate] )",
                "    )",
                ")"
              ],
              "ordinal": 7
            },
            {
              "name": "ITD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalDate] )",
                "    )",
                ")"
              ],
              "ordinal": 8
            },
            {
              "name": "Prior Per ITD",
              "description": "Prior Period Inception To Date",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalPriorPeriodYear] )",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalPPDate] )",
                "    )",
                ")"
              ],
              "ordinal": 9
            },
            {
              "name": "YTotal",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "    )",
                ")"
              ],
              "ordinal": 10
            },
            {
              "name": "PY YTotal",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] ) - 1",
                "    )",
                ")"
              ],
              "ordinal": 11
            },
            {
              "name": "PY",
              "description": "Prior Year",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalDate] >= MIN( Calendar[FiscalPYDate] )",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalPYDate] )",
                "    )",
                ")"
              ],
              "ordinal": 12
            },
            {
              "name": "PY MTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalPeriod]",
                "            = MAX( Calendar[FiscalPeriod] ) - 12",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalPYDate] )",
                "    )",
                ")"
              ],
              "ordinal": 13
            },
            {
              "name": "PY QTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalQuarter]",
                "            = MAX( Calendar[FiscalQuarter] ) - 4",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalPYDate] )",
                "    )",
                ")"
              ],
              "ordinal": 14
            },
            {
              "name": "PY YTD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] ) - 1",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalPYDate] )",
                "    )",
                ")"
              ],
              "ordinal": 15
            },
            {
              "name": "PY ITD",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] ) - 1",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalPYDate] )",
                "    )",
                ")"
              ],
              "ordinal": 16
            },
            {
              "name": "Rolling 12",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalPeriod]",
                "            >= MAX( Calendar[FiscalPeriod] ) - 11",
                "            && Calendar[FiscalPeriod]",
                "            <= MAX( Calendar[FiscalPeriod] )",
                "            && Calendar[FiscalDate] <= MAX( Calendar[FiscalDate] )",
                "    )",
                ")"
              ],
              "ordinal": 17
            },
            {
              "name": "P01",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 1",
                "    )",
                ")"
              ],
              "ordinal": 18
            },
            {
              "name": "P02",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 2",
                "    )",
                ")"
              ],
              "ordinal": 19
            },
            {
              "name": "P03",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 3",
                "    )",
                ")"
              ],
              "ordinal": 20
            },
            {
              "name": "P04",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 4",
                "    )",
                ")"
              ],
              "ordinal": 21
            },
            {
              "name": "P05",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 5",
                "    )",
                ")"
              ],
              "ordinal": 22
            },
            {
              "name": "P06",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 6",
                "    )",
                ")"
              ],
              "ordinal": 23
            },
            {
              "name": "P07",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 7",
                "    )",
                ")"
              ],
              "ordinal": 24
            },
            {
              "name": "P08",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 8",
                "    )",
                ")"
              ],
              "ordinal": 25
            },
            {
              "name": "P09",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 9",
                "    )",
                ")"
              ],
              "ordinal": 26
            },
            {
              "name": "P10",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 10",
                "    )",
                ")"
              ],
              "ordinal": 27
            },
            {
              "name": "P11",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 11",
                "    )",
                ")"
              ],
              "ordinal": 28
            },
            {
              "name": "P12",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 12",
                "    )",
                ")"
              ],
              "ordinal": 29
            },
            {
              "name": "P13",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 13",
                "    )",
                ")"
              ],
              "ordinal": 30
            },
            {
              "name": "P14",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[FiscalYear]",
                "            = MAX( Calendar[FiscalYear] )",
                "            && Calendar[FiscalPeriod] = 14",
                "    )",
                ")"
              ],
              "ordinal": 31
            },
            {
              "name": "PP",
              "expression": [
                "// Tom Sampson © Clutch.Net 2023 MIT License",
                "// 2023-09-17 00:15:34",
                "CALCULATE(",
                "    SELECTEDMEASURE( ),",
                "    FILTER(",
                "        ALL( Calendar ),",
                "        Calendar[Year] = ",
                "            IF(",
                "                MAX(Calendar[FiscalPeriod]) = 1,",
                "                MAX(Calendar[FiscalYear]) - 1,",
                "                MAX(Calendar[FiscalYear])",
                "            )",
                "            && Calendar[FiscalPeriod] = ",
                "            IF(",
                "                MAX(Calendar[FiscalPeriod]) = 1,",
                "                12,",
                "                MAX(Calendar[FiscalPeriod]) - 1",
                "            )",
                "    )",
                ")"
              ],
              "ordinal": 32
            }
          ],
          "precedence": 56
        },
        "columns": [
          {
            "name": "Temporal Scope",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ae5959f-3140-4130-a5fc-db04e3b00928",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "d56d32f2-ffdc-4d03-b1db-8026f8e23092",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "c2a458e5-3b67-4275-aaa6-b02fee2c2f19",
        "partitions": [
          {
            "name": "TemporalCalculationGroup",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_03dee372-2887-46e3-a805-4571883844a7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "982e504b-9e7f-4817-9bbf-930ef7b2a95c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "49b1dbc5-5f7c-492e-982e-432e6d8b5d93",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b74bb37e-3571-44ff-a81e-b446a475b869",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "660e1819-55b2-43d5-9b46-34eff7ce10e0",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "38d9248a-e21b-420b-a36f-3eca856952e6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9f71f0eb-6a0f-4c24-9dc4-8f0236a54afd",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5087b82e-650b-4afd-8cad-d3c1fb1577c4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "07c893fa-e0fb-430e-92a7-a1294c4d45e3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "9eeb118f-b3a1-4c45-b91d-bb9976d4bfb9",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "473bac6c-a058-493b-a1b0-690ed9d04747",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "aea79d94-9f85-4697-aedf-156e169ef307",
                "ordinal": 3
              }
            ],
            "lineageTag": "3037723c-06bd-41a8-a44a-3a0d38fc954f"
          }
        ],
        "isHidden": true,
        "lineageTag": "7fa49c0c-33cd-4935-a5f3-aa06808d201b",
        "partitions": [
          {
            "name": "LocalDateTable_03dee372-2887-46e3-a805-4571883844a7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[PPDate])), 1, 1), Date(Year(MAX('Calendar'[PPDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_087140e2-8c67-4ae1-924c-877a5c633c8d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "74fb4361-aaa0-41c5-a135-d9445fe8cbfc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b740f597-504a-4a8d-83d9-6b713321127f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a470eb1a-1b9b-4635-950f-35ddc1ee9545",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3008bacd-5dc2-45c3-b3ee-335f901f2103",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e381dc46-7305-496f-8499-e89e1161c45c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6dfff3be-6ed1-4582-bd79-da530c452a9e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a4c7a1fa-3d8a-44e1-ae66-5000838dd10a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "10cf6c84-bb47-49e1-a3ce-ea55c518a475",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "41eec03d-0ee3-4cd6-be94-d2625af10905",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "fbdcea27-ea11-40d4-b12c-838675c252e8",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "9d5b6ec5-9688-4223-9eaf-4acbbded765a",
                "ordinal": 3
              }
            ],
            "lineageTag": "4a6f562f-253e-4ffc-a9af-2a4c0c2d0648"
          }
        ],
        "isHidden": true,
        "lineageTag": "2383ea5d-cd3b-4d0c-aed1-72df6dd6f887",
        "partitions": [
          {
            "name": "LocalDateTable_087140e2-8c67-4ae1-924c-877a5c633c8d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[PQDate])), 1, 1), Date(Year(MAX('Calendar'[PQDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_70a5489d-f80c-4199-9137-22032995a46a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e1d8ede0-008c-43a5-8bc3-b2886dfd7e7d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ba7236c9-be6c-4d28-95ec-c07bd70aee08",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "76f43d78-5ad4-4461-a0f7-f543cad3befb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "87c1fd49-41a6-4b91-b7bb-de981aec96d0",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "25c3eac0-6b7e-4a41-acd8-3754c02b70c7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "11d91720-53f1-4e3e-9f75-df586cc91ddd",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "977461a7-aeb9-4349-99ee-b187acaff40b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4c287aa9-1cc6-43ad-8d50-d3c70a0de6fa",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d97dfea1-179e-484d-b9b9-11a18f2a7ed2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7911bfe9-3722-4147-ba61-03edfd326bdb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "62288751-942d-4b21-9d45-85f3dc36d67c",
                "ordinal": 3
              }
            ],
            "lineageTag": "1e0a54c8-a557-4725-a988-532e6cb4ac3f"
          }
        ],
        "isHidden": true,
        "lineageTag": "3f84fc32-1005-4919-a1b1-e3afacedca34",
        "partitions": [
          {
            "name": "LocalDateTable_70a5489d-f80c-4199-9137-22032995a46a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[PYDate])), 1, 1), Date(Year(MAX('Calendar'[PYDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_21888ed1-f392-4961-87ce-7ba785fc873f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bbcb3c52-4431-494a-8be4-5e3b3b0a201a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ec814cca-f9da-46d1-8933-249976d43fb5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "50e8f1d5-9afe-4c18-a559-a43af61f6348",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4a8a4ff3-2408-4918-a3e8-53d8be02e5ca",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f751d92e-0c61-4c86-9958-94058eec9a6d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "32a1ac4d-0c3c-4c0a-a579-9e3e91ff2947",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "da7b7333-5561-404b-a052-b9c84da44bbe",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2ed3e673-8245-4c5f-8786-c445530511fd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5d93a245-5ed8-405f-a68b-f0dab7694141",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "81bd7d34-6c28-4c7a-af75-76dd0c1fc5f2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fdc4edec-0f98-4abb-86cf-08d427a5bf82",
                "ordinal": 3
              }
            ],
            "lineageTag": "5119c05d-7f36-4048-b1fe-3381e1de5a68"
          }
        ],
        "isHidden": true,
        "lineageTag": "9d4a8b18-202d-4b6e-b757-2c90d7bf0e5a",
        "partitions": [
          {
            "name": "LocalDateTable_21888ed1-f392-4961-87ce-7ba785fc873f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[FiscalDate])), 1, 1), Date(Year(MAX('Calendar'[FiscalDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_52b355b8-60be-40d8-bb59-7ca60ba849df",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "56fdddbf-44d3-44fc-90a7-035d8c573f38",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "de4e9d95-8b32-40bc-a4e8-64cbf4cbc8e0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5b795dc3-3cd9-4554-baca-e4c43baaf0e4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8a3e9ea1-8479-4b54-93cf-389a1d72b787",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d01a05ea-7803-4ac1-8d34-f8a0b9013738",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7bc3610c-8822-430e-8d48-366872149772",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5426b21a-20d7-4a02-b33b-0c3c6bbb868b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a7ba4d74-eb7c-4412-96c2-9115818783b9",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d6946a52-9649-474f-a9cf-d5e00bac5c55",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1a83f55e-18b1-45ff-ac05-253ae29140ef",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f205f1bd-0b62-40d7-b4eb-e59be7f129ad",
                "ordinal": 3
              }
            ],
            "lineageTag": "962ecb9c-43d6-4f76-9441-0336914e1f5f"
          }
        ],
        "isHidden": true,
        "lineageTag": "c976718b-6d4d-48b1-b48b-2bbee721ebb0",
        "partitions": [
          {
            "name": "LocalDateTable_52b355b8-60be-40d8-bb59-7ca60ba849df",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[MonthYearDate])), 1, 1), Date(Year(MAX('Calendar'[MonthYearDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}